
<?php
//Mage::getSingleton('core/session')->setaddfree(1);
//echo "--" .$currentcodeapplied = Mage::getSingleton('core/session')->getCouponcodeapplied();
?>
<style type="text/css">
.onsale-category-container {
    top: 275px !important;
    left: 125px !important;
}
div.custom-onsale-category-label-text {
    left: 3px!important;
    top: 20px !important;
    font-size: 19px !important;
}
@media only screen and (max-width: 767px) {
    .actions > button {
    float: left;
}
.regular-price {
    float: left;
}
    .onsale-category-container {
      top: 245px !important;
    left: 87px !important;
}
.products-grid li.item {
    min-height: 320px;
}
}
@media only screen and (max-width: 479px) {
    .onsale-category-container {
    top: 320px !important;
    left: 170px !important;
}
}

</style>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    
?>
<?php if(!$_productCollection->count()): ?>
    <?php echo $this->getToolbarHtml();?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div class="category-products">
    <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_top.phtml')->toHtml(); ?> 
    
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
    
            <?php
                if($_product->getsmall_image() != 'no_selection'){
                    $imageurl = $this->helper('catalog/image')->init($_product, 'small_image')->resize(252).$_product->getsmall_image();
                }else{
                    $imageurl = Mage::getBaseurl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'catalog/product/placeholder/default/placeholder.jpg';
                }
            ?>
    
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php if($_product->getUnilabRx() == 1) :  ?>
                    <div class="productrx"></div>
                <?php endif; ?>
                
            <div class="onsale-category-container-list">
                <?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getUnilabRx() ? $this->__("Requires Prescription") : $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);?>" class="product-image here">
                
                     <img src="<?php echo $imageurl; ?>">
                </a>
            </div>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <div><?php echo $_product->getGenericName()?></div>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>                                                           
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>
                    <p style="text-align: right">
                        <a style="color: #07c;" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More...') ?></a>
                    </p>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                           <!-- <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li> -->
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                           <?php /* <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li> */ ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_iterator = 0; ?>
        <ul class="products-grid">    
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            
            <?php
                if($_product->getsmall_image() != 'no_selection'){
                    $imageurl = $this->helper('catalog/image')->init($_product, 'small_image')->resize(252).$_product->getsmall_image();
                }else{
                    $imageurl = Mage::getBaseurl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'catalog/product/placeholder/default/placeholder.jpg';
                }
            ?>
        
            <li class="item">
                
                <?php if($_product->getUnilabRx() == 1) : ?>
                    <div class="productrx"></div>
                <?php endif; ?>
                
                <div class="pro_topadst">
                    <div class="onsale-category-container-list" style="float:none;">
                    <?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getUnilabRx() ? $this->__("Requires Prescription") : $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);?>" class="product-image">
                    
                        <img src="<?php echo $imageurl; ?>">    
            
                    </a>
                    </div>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <div class="genericname"><?php echo $_product->getGenericName()?></div>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                         
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>   <!--  , setLocation('<?php echo $_product->getProductUrl() ?>') default --> 
                <button type="button" id="btncart" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showmodal('<?php echo $_product->getsku();?>','<?php echo $this->getAddToCartUrl($_product) ?>')" ><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>

                        <?php endif; ?>
                    </ul>
                </div>
            </li>  

        <?php endforeach ?>
        
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        
        <?php       
        
            echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_bottom.phtml')->toHtml();          

        ?>
        
    </div>
</div>

 <script type="text/javascript">
 jQuery.noConflict();

function showmodal(sku, location){
    jQuery.post("<?php echo Mage::getBaseUrl()?>monthlyproducthighlight/checkpromo/passsku",{
    
            //sku: jQuery('#btncart').attr('data-sku')
            sku: sku,
            loc: location
        },

        function (dataRes)
        {
            //NO PROMO
            var ObjRes = jQuery.parseJSON(dataRes);

            var sku = ObjRes.eskeyu;
            var url = ObjRes.url;
            if(ObjRes.success == true){

            jQuery.fancybox.showLoading();
            jQuery.ajax({
                type:"GET",
                url:url,
                success:function(data){
                     window.location.href = "<?php echo Mage::getBaseurl();?>checkout/cart/";
                }
             });

            }else{
                // PROMO
                //jQuery('#modal_terms .terms-ag').attr('onclick',"addtocart('"+sku+"')");
                jQuery('#modal_terms .terms-dg').attr('onclick',"addtocart('"+location+"')");
                jQuery('#modal_terms button').attr('data-sku',sku);
                jQuery('#modal_terms button').attr('data-loc',location);
                jQuery('#modal_terms').modal(sku);
            }
        }
    );
}

function validatecode(){
    jQuery.post("<?php echo Mage::getBaseUrl()?>monthlyproducthighlight/checkpromo/validatecoupon",{

        promocode: jQuery('#inp-mod').val(),
        location: jQuery('.terms-ag').attr('data-loc'),
        sku: jQuery('.terms-ag').attr('data-sku')
    },

    function (dataRess)
        {
            var ObjRes = jQuery.parseJSON(dataRess);

            var what = ObjRes.what;

            var loca = ObjRes.loc;
            if(ObjRes.success == true){
                //COUPON CODE MATCHED
                    jQuery.fancybox.showLoading();
                    jQuery.ajax({
                        type:"GET",
                        url:loca,
                        success:function(data){
                             window.location.href = "<?php echo Mage::getBaseurl();?>checkout/cart/";
                        }
                     });

            }else{
                 alert(what);

            }
        }
    );
}

function addtocart(location){
    jQuery.post("<?php echo Mage::getBaseUrl()?>monthlyproducthighlight/checkpromo/addornot",{
    dataloc: jQuery('.terms-dg').attr('data-loc')
    },

    function   (datadata)
    {
    var ObjRes = jQuery.parseJSON(datadata);

        if(ObjRes.success == true){

            jQuery.fancybox.showLoading();
            jQuery.ajax({
                type:"GET",
                url:location,
                success:function(data){
                     window.location.href = "<?php echo Mage::getBaseurl();?>checkout/cart/";
                }
             });
        }
    }
    );
}



 </script>

<style type="text/css">
#modal_terms, #modal_waiver {display:none;}

/* Overlay */
#simplemodal-overlay {background-color:#000;}

/* Container */
/*#simplemodal-container {height:360px; width:600px; color:#bbb; background-color:white; padding:12px; top:20px !important; width:70% !important;}*/
#simplemodal-container {
    height: 360px;
    width: 600px;
    color: #000;
    background-color: white;
    padding: 12px;
    top: 20% !important;
    width: 30% !important;
    left: 35% !important;
    height: 26% !important;
    border-radius: 0.5em;
}

.term-text {
    max-height: 230px !important;
    height: 230px !important;
}
.ag_dg {
    background-color: black;
    color: white;
    width: 30%;
    margin-top: 8%;
}

input.inp-mod {
    margin-left: 10%;
}

label.lab-mod {
    margin-left: 7%;
	font-weight: bold;
}

.btn-cart{
    /* margin-top: 8%; */
}

.btn-coupon{
	margin: 10px;
}

#modal_terms{
    border: 1px solid #eee;
    padding: 10px;
}

.btn-container{
	text-align:center; 
}

.modal-msg{
	text-align:center;
	color: #053167;
}

span.enter {
    font-weight: bold;
}
</style>

<script type='text/javascript' src='<?php echo $this->getSkinUrl(); ?>js/jquery.simplemodal.js'></script>
<div id="modal_terms">
    <div class="txtarea">
		<div style="text-align: center;"><input type="text" class="inp-mod" id="inp-mod"></input></div>
		<p class="modal-msg">
			<span class="enter">Enter Promo Code to get FREE</span> <br>
			Trisopure 60ml Travel Buddy Pack <br>
			or <br>
			Ceelin Drops 10ml

        <?php //echo Mage::getSingleton('core/session')->getprodloc();?>
		</p>
		
		
        <div class="btn-container">
            <button class="button btn-cart terms-ag btn-coupon" data-loc="" data-sku="" data-btn="1" onclick="validatecode()">APPLY PROMO CODE</button>
            <button class="button btn-cart terms-dg  btn-coupon" data-loc="" data-sku="" data-btn="0" onclick="addtocart('<?php echo Mage::getSingleton('core/session')->getprodloc() ?>')">NO PROMO CODE</button>                
        </div>
    </div>
</div>
<?php endif; ?>
