<?php
    
	$categoryid = Mage::getSingleton('core/session')->getCategoryId();
	
	if(isset($categoryid))
	{
		$_productCollection = Mage::getSingleton('catalog/category')->load($categoryid)
				->getProductCollection()
				->addAttributeToSelect('*');		
	}else{
		$_productCollection=$this->getLoadedProductCollection();	
	}	
	
    $_helper = $this->helper('catalog/output');
    

    
?>
<?php if(!$_productCollection->count()): ?>
    <?php echo $this->getToolbarHtml();?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div class="category-products">
    <?php //echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_top.phtml')->toHtml(); ?> 
    <?php echo $this->getToolbarHtml();?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php if($_product->getUnilabRx() == 1) :  ?>
                    <div class="productrx"></div>
                <?php endif; ?>
        
            <?php // Product Image ?>
            <div class="onsale-category-container-list">
                <?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getUnilabRx() ? $this->__("Requires Prescription") : $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);?>" class="product-image here"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(252); ?>" width="252" height="252" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            </div>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <div><?php echo $_product->getGenericName()?></div>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart " onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <p><button type="button" title="<?php echo $this->__('View Product') ?>" class="button btn-view" ><span><span><?php echo $this->__('View Product') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                           <!-- <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li> -->
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                           <?php /* <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li> */ ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_iterator = 0; ?>
        <ul class="products-grid">    
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li class="item">
                
                
                <?php if($_product->getUnilabRx() == 1) :  ?>
                    <div class="productrx"></div>
                <?php endif; ?>
                
                <div class="pro_topadst">
                
                    <div class="onsale-category-container-list" style="float:none;">
                    <?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getUnilabRx() ? $this->__("Requires Prescription") : $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(252); ?>" width="252" height="252" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <div class="genericname"><?php echo $_product->getGenericName()?></div>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                      <!--  <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php //echo $this->__('Add to Cart') ?></span></span></button>-->
                  <button type="button" id="btncart" returnId="<?php echo $_product->getId(); ?>" returnName="<?php echo $_product->getName(); ?>" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" ><span><span><?php echo $this->__('Add to Cart') ?></span></span></button> 
                  <button type="button" id="btncart" title="<?php echo $this->__('View Product') ?>" class="button btn-view" returnUrl="<?php echo $_product->getProductUrl() ?>"><span><span><?php echo $this->__('View Product') ?></span></span></button> 
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                           <!-- <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li> -->
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                           <?php /*  <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li> */ ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>  
        <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_bottom.phtml')->toHtml(); ?>
    </div>
</div>
<?php //endif; ?><!--comment !-->


<?php endif; ?>

<!-- The Modal -->
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">×</span>
      <h2>Work-Place</h2>
    </div>
    <div class="modal-body">
      <p><span id="prodName"></span> was added to your shopping cart</p>
    </div>
    <div class="modal-footer">
      <button type="button"title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-cshopping"><span><?php echo $this->__('Continue Shopping') ?></span></button>
      <button type="button" returnUrl="<?php echo Mage::helper('checkout/url')->getCheckoutUrl() ?>" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-checkout" ><span><?php echo $this->__('Proceed to Checkout') ?></span></button>
    </div>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function() {
   $(document).on('click','.btn-view',function(){
        window.location = $(this).attr('returnUrl');
   });

   $(document).on('click','.btn-cart',function(){
        var product = $(this).attr('returnId');
        var productName = $(this).attr('returnName');
        $.ajax({
        type: 'Post',
        url:'<?php echo Mage::getBaseUrl()?>checkout/cart/addtoCart',
        data: {
            product: product
        },
        }).done(function(data){
            if(data == 'success'){
            $("#prodName").html(productName);    
            var count = $("#item_count").html();
            count = Number(count) + Number(1);
            $("#item_count").html(count);  
            $("#myModal").show();
            }
        });
    });

   $(document).on('click','.close',function(){
        $("#myModal").hide();
    });

    $(document).on('click','.btn-cshopping',function(){
        $("#myModal").hide();
    });

    $(document).on('click','.btn-checkout',function(){
        window.location = $(this).attr('returnUrl');
    });
   
});
</script>