<?php
    
    $categoryid = Mage::getSingleton('core/session')->getCategoryId();

    $_productCollection=$this->getLoadedProductCollection($categoryid);      
  
    $_helper = $this->helper('catalog/output');

    $pagetitle = $this->getLayout()->getBlock('head')->getTitle();
    $pageArr = explode(' - ', $pagetitle);
    $searchArr = explode(' ', $pagetitle);

?>
<script>
	<?php if(count($pageArr) == 1) :?>

        digitalData.page={ 
            pageInfo:{
                pageName:"ch:<?php echo $pageArr[0]; ?>",
                site: "clickhealth"         
            },
            category:{
                pageType:"category",
                primaryCategory:"category", 
                subCategory1: "<?php echo $pageArr[0]; ?>",
                subCategory2: "",
                subCategory3: ""

            }
        }

    <?php endif; ?>

    <?php if(count($pageArr) == 2) :?>
        
        <?php if($pageArr[1] == "Default Category") :?>
        
        digitalData.page={ 
            pageInfo:{
                pageName:"ch:<?php echo $pageArr[0]; ?>",
                site: "clickhealth"         
            },
            category:{
                pageType:"category",
                primaryCategory:"category", 
                subCategory1: "<?php echo $pageArr[0]; ?>",
                subCategory2: "",
                subCategory3: ""

            }
        }
        
        <?php else: ?>
        
        digitalData.page={ 
            pageInfo:{
                pageName:"ch:<?php echo $pageArr[1]; ?>:<?php echo $pageArr[0]; ?>",
                site: "clickhealth"         
            },
            category:{
                pageType:"sub-category",
                primaryCategory:"category", 
                subCategory1: "<?php echo $pageArr[1]; ?>",
                subCategory2: "<?php echo $pageArr[0]; ?>",
                subCategory3: ""
                
            }
        }
        
        <?php endif; ?>
        
    <?php endif; ?>
    
    <?php if(count($pageArr) == 3) :?>
        
        digitalData.page={ 
            pageInfo:{
                pageName:"ch:<?php echo $pageArr[1]; ?>:<?php echo $pageArr[0]; ?>",
                site: "clickhealth"         
            },
            category:{
                pageType:"sub-category",
                primaryCategory:"category", 
                subCategory1: "<?php echo $pageArr[1]; ?>",
                subCategory2: "<?php echo $pageArr[0]; ?>",
                subCategory3: ""
                
            }
        }
    <?php endif; ?>
</script>

<?php if(!$_productCollection->count()): ?>
    <?php echo $this->getToolbarHtml();?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

	<div class="category-products">
		<?php //echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_top.phtml')->toHtml(); ?> 
		<?php echo $this->getToolbarHtml();?>
		
		<?php // List mode ?>
		<?php if($this->getMode()!='grid'): ?>
		
			<?php $_iterator = 0; ?>
		
			<ol class="products-list" id="products-list">
				<?php 
				$i=0;	
					
				foreach ($_productCollection as $_product): 
					
					$i++;
					$brand    = $_product->getUnilabBrand();
					$size     = $_product->getUnilabSize();

					$unilab_brand_text = Mage::getModel('admincontroller/convertattrib')->idtotext($_product->getId(), $brand, 'unilab_brand');
					$unilab_size_text = Mage::getModel('admincontroller/convertattrib')->idtotext($_product->getId(), $size, 'unilab_size');
				?>
				
					<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
					
						<?php if($_product->getUnilabRx() == 1) :  ?>
							<div class="productrx"></div>
						<?php endif; ?>
			
						<?php // Product Image ?>
						<div class="onsale-category-container-list">
							<?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getUnilabRx() ? $this->__("Requires Prescription") : $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true);?>" class="product-image <?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnName="<?php echo $_product->getName(); ?>" sequence="<?php echo $i;?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(252); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" /></a>
						</div>
						
						<?php // Product description ?>
						<div class="product-shop">
							<div class="f-fix">
								<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="<?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnName="<?php echo $_product->getName(); ?>" sequence="<?php echo $i;?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
								<div><?php echo $_product->getGenericName()?></div>

								<div class="health-plus-catalog">
									<?php
										$storeid 		= 	Mage::app()->getStore()->getStoreId();
										$healthplusEnabled = Mage::getStoreConfig('healthplus/healthplussettings/enabled', $storeid);
							
										if($healthplusEnabled == 1)
										{
											if(Mage::getConfig()->getModuleConfig('Unilab_Healthplus')->is('active', 'true'))
											{
												$attributeValue = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeText('unilab_healthplus');    

												if($attributeValue == 'Yes')
												{
													?><img src="<?php echo $this->getSkinUrl('images/health-plus-logo.png'); ?>" alt="health plus"/><?php   
												}          
											}
										 }
									?>
								</div>

								<?php if($_product->getRatingSummary()): ?>
									<?php echo $this->getReviewsSummaryHtml($_product) ?>
								<?php endif; ?>

								<?php echo $this->getPriceHtml($_product, true) ?>
								
								<?php if($_product->isSaleable()): ?>
								
									<?php if($_product->getUnilabRx()):?>
											<button type="button" id="addToCart" title="<?php echo $buttonTitle ?>" class="button btn-cartrx askPrescription" returnUrl="<?php echo $this->getSubmitUrl($_product);?>" returnId="<?php echo $_product->getId();?>" returnName="<?php echo $_product->getName(); ?>" returnMoq="1" itemprice="<?php echo $_product->getPrice(); ?>" itemsku="<?php echo $_product->getSku();?>" itembrand="<?php echo $_product->getUnilabBrand();?>" itemsize="<?php echo $unilab_size_text; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button><br>
									<?php else: ?>

											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart " attribset="<?php echo $_product->getTypeID();?>" returnUrl="<?php echo $_product->getProductUrl() ?>" returnName="<?php echo $_product->getName(); ?>" returnId="<?php echo $_product->getId();?>" itemprice="<?php echo $_product->getPrice(); ?>" itemsku="<?php echo $_product->getSku();?>" itembrand="<?php echo $_product->getUnilabBrand();?>" itemsize="<?php echo $unilab_size_text; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button><br>
									
									<?php endif; ?>
									
									<button type="button" id="btncart2" title="<?php echo $this->__('View Product') ?>" class="button btn-view <?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnUrl="<?php echo $_product->getProductUrl() ?>" returnName="<?php echo $_product->getName(); ?>" sequence="<?php echo $i;?>"><span><span><?php echo $this->__('View Product') ?></span></span></button> 
								
								<?php else: ?>
									
									<!-- <p class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></p> -->
									<button type="button" title="<?php echo $this->__('Out of Stock') ?>" class="button btn-cart " disabled><span><span><?php echo $this->__('Out of Stock') ?></span></span></button><br>
									<button type="button" id="btncart2" title="<?php echo $this->__('View Product') ?>" class="button btn-view <?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnUrl="<?php echo $_product->getProductUrl() ?>" returnName="<?php echo $_product->getName(); ?>" ><span><span><?php echo $this->__('View Product') ?></span></span></button>
								
								<?php endif; ?>
								
								<div class="desc std">
									<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
								</div>
								
								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
									   <!-- <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li> -->
									<?php endif; ?>
									
									
									<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									   <?php /* <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li> */ ?> 
									<?php endif; ?>
								</ul>
							</div>
						</div>	
					</li>
				<?php endforeach; ?>
			</ol>
			
			<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

		<?php else: ?>

			<?php // Grid Mode ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $this->getColumnCount(); ?>
			<?php $_iterator = 0; ?>
			
			<ul class="products-grid">  
			<?php 
				$i=0; 
				
				foreach ($_productCollection as $_product): 
				
					$i++;     
					$brand    = $_product->getUnilabBrand();
					$size     = $_product->getUnilabSize();

					$unilab_brand_text = Mage::getModel('admincontroller/convertattrib')->idtotext($_product->getId(), $brand, 'unilab_brand');
					$unilab_size_text = Mage::getModel('admincontroller/convertattrib')->idtotext($_product->getId(), $size, 'unilab_size');    
			?>

					<li class="item">
						
						<?php if($_product->getUnilabRx() == 1) :  ?>
							<div class="productrx"></div>
						<?php endif; ?>
						
						<div class="pro_topadst">
						
							<div class="onsale-category-container-list" style="float:none;">
								<?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getUnilabRx() ? $this->__("Requires Prescription") : $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true);?>" class="product-image <?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnName="<?php echo $_product->getName(); ?>" sequence="<?php echo $i;?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(252); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" /></a>
							</div>
							
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="<?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnName="<?php echo $_product->getName(); ?>" sequence="<?php echo $i;?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							
							<div class="genericname"><?php echo $_product->getGenericName()?></div>
						
							<div class="ratings">
								<?php if($_product->getRatingSummary()): ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>  
								<?php endif; ?>
							</div>

							<div class="health-plus-catalog">
								<?php
									$storeid 		= 	Mage::app()->getStore()->getStoreId();
									$healthplusEnabled = Mage::getStoreConfig('healthplus/healthplussettings/enabled', $storeid);
						
									if($healthplusEnabled == 1)
									{
										if(Mage::getConfig()->getModuleConfig('Unilab_Healthplus')->is('active', 'true'))
										{
											$attributeValue = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeText('unilab_healthplus');    

											if($attributeValue == 'Yes')
											{
												?><img src="<?php echo $this->getSkinUrl('images/health-plus-logo.png'); ?>" alt="health plus"/><?php   
											}          
										}
									 }
								?>
						   </div>
							<?php echo $this->getPriceHtml($_product, true) ?> 
						</div>
						
						<div class="actions">
							<?php if($_product->isSaleable()): ?>
							
								<?php if($_product->getUnilabRx()):?>
									<button type="button" id="addToCart" title="<?php echo $buttonTitle ?>" class="button btn-cartrx askPrescription" returnUrl="<?php echo $this->getSubmitUrl($_product);?>" returnId="<?php echo $_product->getId();?>" returnName="<?php echo $_product->getName(); ?>" returnMoq="1" itemprice="<?php echo $_product->getPrice(); ?>" itemsku="<?php echo $_product->getSku();?>" itembrand="<?php echo $unilab_brand_text;?>" itemsize="<?php echo $unilab_size_text; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php else: ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart " attribset="<?php echo $_product->getTypeID();?>" returnUrl="<?php echo $_product->getProductUrl() ?>" returnId="<?php echo $_product->getId();?>" returnName="<?php echo $_product->getName(); ?>" itemprice="<?php echo $_product->getPrice(); ?>" itemsku="<?php echo $_product->getSku();?>" itembrand="<?php echo $unilab_brand_text;?>" itemsize="<?php echo $unilab_size_text; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php endif; ?> 
								
								<button type="button" id="btncart2" title="<?php echo $this->__('View Product') ?>" class="button btn-view <?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnUrl="<?php echo $_product->getProductUrl() ?>" returnName="<?php echo $_product->getName(); ?>" sequence="<?php echo $i;?>"><span><span><?php echo $this->__('View Product') ?></span></span></button> 
							
							<?php else: ?>
								
								<!-- <p class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></p> -->
								<button type="button" title="<?php echo $this->__('Out of Stock') ?>" class="button btn-cart " disabled><span><span><?php echo $this->__('Out of Stock') ?></span></span></button>
								<button type="button" id="btncart2" title="<?php echo $this->__('View Product') ?>" class="button btn-view <?php if($searchArr[0] == 'Search'):?>clickthrough<?php endif; ?>" returnUrl="<?php echo $_product->getProductUrl() ?>" returnName="<?php echo $_product->getName(); ?>"><span><span><?php echo $this->__('View Product') ?></span></span></button> 
							
							<?php endif; ?>
							
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
								   <!-- <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li> -->
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								   <?php /*  <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li> */ ?>
								<?php endif; ?>
							</ul>
						</div>
					</li>  
				<?php endforeach ?>
			</ul>
			
			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
			
		<?php endif; ?>

		<div class="toolbar-bottom">
			<?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_bottom.phtml')->toHtml(); ?>
		</div>
	</div>
<?php //endif; ?><!--comment !-->
<?php endif; ?>


<!-- Loading Icon -->
<div id="loading-icon">
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/default/unilab2/images/loading-icon.gif">
</div>
<!-- The Modal -->
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <h2>Clickhealth</h2>
    </div>
    <div class="modal-body">
      <p><span id="prodName"></span> was added to your shopping cart</p>
    </div>
    <div class="modal-footer">
      <button type="button"title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-cshopping"><span><?php echo $this->__('Continue Shopping') ?></span></button>
      <button type="button" returnUrl="<?php echo Mage::helper('checkout/url')->getCartUrl() ?>" title="<?php echo $this->__('Proceed to Cart') ?>" class="button btn-checkout" ><span><?php echo $this->__('Proceed to Cart') ?></span></button>
    </div>
  </div>
</div>

<script type="text/javascript">    

    var productAddToCartForm = new VarienForm('product_addtocart_form');            
    var disable_submission   = false;           
    var prevent_submission   = false;    

	jQuery(document).ready(function (){ 

		jQuery('.askPrescription').click(function (){

			var url = jQuery(this).attr('returnUrl');
			var product = jQuery(this).attr('returnId');
			var moq = jQuery(this).attr('returnMoq');
			// var product = jQuery(this).attr('returnId');
			var productName = jQuery(this).attr('returnName');

			jQuery('#product_addtocart_form').attr('action',url);
			jQuery('#product').val(product);
			jQuery('#qty').val(moq);
			jQuery.fancybox.showLoading();                  
			
			var prescription_askuser_url  = '<?php echo $this->getUrl('prescription/index/askuser');?>';                    
            //var parameters  =  Form.serialize(this.form);                       
            var parameters = '&form_action='+url;  
            parameters += '&product='+product; 
            parameters += '&qty='+moq; 

            var request = new Ajax.Request(prescription_askuser_url, {                          
                parameters: parameters,               
                onSuccess: function(transport){                                                             

                    if(transport.status == 200) {                                   
  
                        var response = transport.responseText.evalJSON();                               

                            if(response.proceed_to_cart){                                   
                                //if rx product is already in cart
								// jQuery('#product_addtocart_form').submit(); 
                                jQuery("#loading-icon").show();
								
								jQuery.post("<?php echo Mage::getBaseUrl()?>checkout/cart/addtoCart",
								{
									product: product			

								},function (data)
								{
									var objresponse = jQuery.parseJSON(data);
										
									if(objresponse.msg == 'success')
									{
										jQuery("#prodName").html(productName);    
										var count = jQuery("#item_count").html();
										count = Number(count) + Number(1);
										jQuery("#item_count").html(count); 
										jQuery("#loading-icon").hide(); 
										jQuery("#myModal").show();
										
										var sku = jQuery(this).attr('itemsku');
										var brand = jQuery(this).attr('itembrand');
										var size = jQuery(this).attr('itemsize');
										var itemprice = jQuery(this).attr('itemprice');

                                        //ADOBE Analytics
                                        digitalData.cartValue = itemprice;
                                        
                                        if(objresponse.cartcount == 0){
                                            digitalData.events = "scOpen,scAdd";
                                        }else{
                                            digitalData.events = "scAdd";
                                        }
                                        
                                        digitalData.product=[{ 
                                            productInfo: {
                                                productID: sku,
                                                productName: productName,
                                                productBrand: brand,
                                                productSize: size
                                            }
                                        }]
                                        
                                        _satellite.track('cart-add');

									}

								});	
									
                            }else{                                          
								// alert('false');
                                showDialog(response.askuser_dialog);                                                                    
                                askUserControls(response);                               
                            }                                                           
                        }                      
                    },                      

                    onFailure: '',                      
                    onComplete: function(){

                        jQuery.fancybox.hideLoading();                      
                    }                   
            });                    
		});
	});


//<![CDATA[         
    var askUserControls = function(response) {              

        jQuery("#no_prescription").click(function(){                    

            showDialog(response.cancel_dialog);                                         
            jQuery("#btnCancelPrescription").click(function(){                      
                jQuery.fancybox.close();                                
            });             
        });                 

        jQuery("#has_prescription").click(function(){                           
            prescriptionControls(response);                                             
        });         
		
    }            

    var showConfirmCancelPrescriptionDialog = function(response) {                          
	
        showDialog(response.cancel_trans_dialog);                               

        jQuery("#btnCancelPrescriptionTransaction").click(function(){                   
            jQuery.fancybox.close();                
        });                 

        jQuery("#btnCancelPrescriptionCancelTransaction").click(function(){                  
            prescriptionControls(response);             
        });                             
    }           

    
    var prescriptionControls = function(response) {                     

        showDialog(response.prescription_dialog);               

        jQuery("#cancel_prescription").click(function(){                    
            showConfirmCancelPrescriptionDialog(response);                                  
        });                 

        prescriptionForm.submit = function(button, url) {                   

            if(disable_submission) {            
                return false;                   
            }                   

            if (prescriptionForm.validator.validate())  {       

                //prevent double submission                     
                if(prevent_submission){                                                     
                    return false;                       
                }                       
         
                prevent_submission = true;   
				
                VarienForm.prototype.submit.bind(prescriptionForm)();                     
            }               
        }           
    }       
    //]]>    
	
    jQuery('.AddToCartNoRx').click(function (){

		jQuery.fancybox.showLoading();

		var url = jQuery(this).attr('returnUrl');
		var product = jQuery(this).attr('returnId');
		var moq = jQuery(this).attr('returnMoq');


		jQuery('#product_addtocart_form').attr('action',url);
		jQuery('#product').val(product);
		jQuery('#qty').val(moq);
		jQuery('#product_addtocart_form').submit();

    });     
</script> 



<script>
   jQuery(document).on('click','.btn-view',function(){
        window.location = jQuery(this).attr('returnUrl');
   });

   jQuery(document).on('click','.close',function(){
        jQuery("#myModal").hide();
    });

    jQuery(document).on('click','.btn-cshopping',function(){
       jQuery("#myModal").hide();
       jQuery("#loading-icon").show();
        location.reload();
    });

    jQuery(document).on('click','.btn-checkout',function(){
        window.location = jQuery(this).attr('returnUrl');

    });

	//Adobe Analytics
	jQuery(document).on('click','.btn-cart',function(){
		
		jQuery("#loading-icon").show();
		var product = jQuery(this).attr('returnId');
		var productName = jQuery(this).attr('returnName');
		var itemprice = jQuery(this).attr('itemprice');
		// Adobe Analytics
		var sku = jQuery(this).attr('itemsku');
		var brand = jQuery(this).attr('itembrand');
		var size = jQuery(this).attr('itemsize');
		var attribset = jQuery(this).attr('attribset');
		var returnUrl = jQuery(this).attr('returnUrl');
		
		if(attribset == "configurable"){
			window.location = returnUrl;
		}
		
		jQuery.post("<?php echo Mage::getBaseUrl()?>checkout/cart/addtoCart",
		{
			product: product			

		},function (data){

			var objresponse = jQuery.parseJSON(data);
			
			if(objresponse.msg == 'success'){
				
				jQuery("#prodName").html(productName);    
				var count = jQuery("#item_count").html();
				count = Number(count) + Number(1);
				jQuery("#item_count").html(count); 
				jQuery("#loading-icon").hide(); 
				jQuery("#myModal").show();

                //ADOBE Analytics
                digitalData.cartValue = itemprice;
                
                if(objresponse.cartcount == "0"){
                    digitalData.events = "scOpen,scAdd";
                }else{
                    digitalData.events = "scAdd";
                }
                
                digitalData.product=[{ 
                    productInfo: {
                        productID: sku,
                        productName: productName,
                        productBrand: brand,
                        productSize: size
                    }
                }]
                
                _satellite.track('cart-add');
			}

		});	
	});

    jQuery(".clickthrough").click(function(){   
        var sequence = jQuery(this).attr('sequence');
        var prodname = jQuery(this).attr('returnName');

        digitalData.page.pageInfo.clickedSearchResult = sequence+"|"+prodname;

        _satellite.track('search-clickthrough');
     
    });

</script>

<!-- AMO Conversion Tags -->
<script type='text/javascript'>
    (function() {
        var f = function() {
              EF.init({ eventType: "transaction",
                        transactionProperties : "ev_Product List=1&ev_transid=<transid>",
                        segment : "27930", 
                        searchSegment : "",
                        sku : "",
                        userid : "940",
                        pixelHost : "pixel.everesttech.net"
                        
                        , allow3rdPartyPixels: 1});
              EF.main();
        };
        window.EF = window.EF || {}; 
        if (window.EF.main) {
            f();
            return;
        }
        window.EF.onloadCallbacks = window.EF.onloadCallbacks || [];
        window.EF.onloadCallbacks[window.EF.onloadCallbacks.length] = f;
        if (!window.EF.jsTagAdded) {
            var efjs = document.createElement('script'); efjs.type = 'text/javascript'; efjs.async = true;
            efjs.src = 'https://www.everestjs.net/static/st.v3.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(efjs, s);
            window.EF.jsTagAdded=1;
        }
    })();
</script>
<noscript><img src="https://pixel.everesttech.net/940/t?ev_Product List=1&ev_transid=<transid>" width="1" height="1"/></noscript>
<!-- AMO Conversion Tags -->