<?php 
$pagetitle = $this->getLayout()->getBlock('head')->getTitle();
?>
<script>
    digitalData.page={ 
        pageInfo:{
            pageName:"ch:customer:register",
            site: "clickhealth"         
        },
		category:{
			pageType:"Customer",
			primaryCategory:"Customer", 
			subCategory1: "Register", 
			subCategory2: "",
			subCategory3: ""

		}
    }

	digitalData.registration={
		formName:"registration:start"
	}
	_satellite.track("registration-start");

</script>

 <div class="account-create">

    <div class="page-title">
        <!-- <h2><?php echo $this->__('Welcome to') ?></h2>
        <h1><?php echo $this->__('Athena') ?></h1> -->
        <h1><?php echo $this->__('Register New Account') ?></h1>
    </div>

    <?php echo $this->getChildHtml('form_fields_before')?>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">

        <div class="fieldset">

            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>

            <hr class="div">

            <ul class="form-list">

                <li class="fields">

                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

                    <div class="input-box">

                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />

                    </div>

                </li>

                <li class="fields">

                    <!-- <div class="field"> -->

                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                        <div class="input-box">

                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />

                        </div>

                    <!-- </div> -->

                    <!-- <div class="field"> -->

                </li>

                <li class="fields">

                

                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>

                        <div class="input-box">

                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />

                        </div>

                    <!-- </div> -->

                </li> 

                <?php // echo $this->getChildHtml('persistent.remember.me'); ?>

            </ul> 

        </div>

        <div class="fieldset">

            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />

            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>

            <hr class="div">

            <ul class="form-list">

                <li class="fields">

                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                </li>



            <?php $_civil_status = $this->getLayout()->createBlock('customer/widget_civilstatus') ?>

            <?php if ($_civil_status->isEnabled()): ?>

                <li class="ddl-reg fields"><?php echo $_civil_status->setCivilStatus($this->getFormData()->getCivilStatus())->toHtml() ?></li>

            <?php endif ?>



            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>

            <?php if ($_taxvat->isEnabled()): ?>

                <li class="ddl-reg fields"><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>

            <?php endif ?>



            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

            <?php if ($_gender->isEnabled()): ?>

                <li class="ddl-reg-gender fields"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>

            <?php endif ?>



            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>

            <?php if ($_dob->isEnabled()): ?>

                <li class="fields"><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>

            <?php endif ?>

            </ul>

        </div>

    <?php // if($this->getShowAddressFields(true)): ?>

        <div class="fieldset">

            <input type="hidden" name="create_address" value="1" />

            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>

            <hr class="div">

            <ul class="form-list">

                <li class="fields">

                    <!-- <div class="field"> -->

                        <label for="company"><?php echo $this->__('Company') ?></label>

                        <div class="input-box">

                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />

                        </div>

                    <!-- </div>                     -->

                </li>

                <li class="fields"> 

                     <!-- <div class="field"> -->

                        <label for="mobile" class="required"><em>*</em><?php echo $this->__('Mobile') ?></label>

                        <div class="input-box">

                            <input type="text" name="mobile" id="mobile" value="<?php echo $this->escapeHtml($this->getFormData()->getMobile()); ?>" title="<?php echo $this->__('Mobile') ?>" maxlength="13"  class="numbersOnly validate-contactnumber-require-one input-text <?php //echo $this->helper('customer/address')->getAttributeValidationClass('mobile') ?>" />

                        </div>

                    <!-- </div> -->

                </li>

               <li class="fields">

                    <!-- <div class="field"> -->

                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

                        <div class="input-box">

                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" maxlength="11"  class="numbersOnly validate-contactnumber-require-one input-text <?php //echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />

                        </div>

                    <!-- </div> -->

                    

                </li>

                <li class="ddl-reg fields">

                    <!-- <div class="field"> -->

                        <label for="country" style="margin: 5px 10px;" class="ddl-reg required"><em>*</em><?php echo $this->__('Country') ?></label>

                        <div class="input-box">

                            <?php echo $this->getCountryHtmlSelect() ?>

                        </div>

                    <!-- </div> -->

                </li>

                <li class="ddl-reg fields">

                    <!-- <div class="field"> -->

                        <label for="region_id" style="margin: 5px 10px;" class="ddl-reg required"><em>*</em><?php echo $this->__('State/Province') ?></label>

                        <div class="input-box">

                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">

                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>

                            </select>

                            <script type="text/javascript">

                            //<![CDATA[

                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");

                            //]]>

                            </script>

                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />

                        </div>

                    <!-- </div> -->

                </li>

                  <li class="ddl-reg fields">

                    <!-- <div class="field"> -->

                        <label for="city" style="margin: 5px 10px;" class="ddl-reg required"><em>*</em><?php echo $this->__('Town/City') ?></label>

                        <div class="input-box">

                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />

                        </div>

                    <!-- </div> -->

                </li>

             

            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>

                <li class="fields">

                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>

                    <div class="input-box">

                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />

                    </div>

                </li>

            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
               <li class="fields">

                    <!-- <div class="field"> -->

                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>

                        <div class="input-box">

                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />

                        </div>

                    <!-- </div> -->

                </li>

            <div style="display:none;">

            <?php for ($_i = 1, $_n = $this->helper('customer/address')->getStreetLines()-1; $_i <= $_n; $_i++): ?>

                <li class="wide">

                    <div class="input-box">

                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />

                    </div>

                </li>

            <?php endfor; ?>

            </div>

            </ul>

            <input type="hidden" name="default_billing" value="1" />

            <input type="hidden" name="default_shipping" value="1" />

        </div>

    <?php //endif; ?> 

        <div class="fieldset">

            <h2 class="legend"><?php echo $this->__('Security Check') ?></h2>

            <hr class="div">

            <ul class="form-list captcha">



                <?php echo $this->getChildHtml('form.additional.info'); ?>

                <?php //echo $this->getChildHtml('persistent.remember.me'); ?>

            </ul>

            <?php //echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

        </div>

        

        <div class="fieldset">

            <hr class="div">

            <ul class="form-list">

                <?php if ($this->isNewsletterEnabled()): ?>

                <li class="control">

                        <div class="input-box div_checkbox">

                            <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('I want to receive email from WPSI and its partners') ?>" value="1" id="is_subscribed" class="checkbox" />

                            <label class="terms" for="is_subscribed"><?php echo $this->__('I want to receive email from WPSI and its partners') ?></label>

                        </div>

                </li>

                <?php endif ?>

                 <?php $_terms = $this->getLayout()->createBlock('customer/widget_terms') ?>

                <?php if ($_terms->isEnabled()): ?>

                    <li class="control"><?php echo $_terms->setAgreeOnTerms($this->getFormData()->getAgreeOnTerms())->toHtml() ?></li>

                <?php endif ?> 

            </ul>

            <div class="clear"></div>

        </div>

        <div class="buttons-set">

            <p class="required"><?php echo $this->__('* Required Fields') ?></p>

            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>

            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button" id="submit-reg"><span><span><?php echo $this->__('Submit') ?></span></span></button>

        </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>

            <input name="context" type="hidden" value="checkout" />

        <?php endif; ?>

    </form>

    <script type="text/javascript"> 

    //<![CDATA[

        var dataForm = new VarienForm('form-validate', true);

		
		jQuery('#submit-reg').click(function(){
			var error_fields = "";
			if (!dataForm.validator.validate()){
				jQuery(".validation-failed").each(function() {
					
					error_fields = error_fields + jQuery(this).attr('id') + "|";
				
				});
				
				
				digitalData.registration={
					formName:"Create Account:Account Management",
					formError: error_fields.slice(0, -1)
				}
				_satellite.track("form-error");

			}
		});
		


        RegionUpdater.prototype.update = RegionUpdater.prototype.update.wrap(function(parentMethod){            

            parentMethod();         

            if(this.countryEl.value == "PH"){               

                if($("mobile") && $("mobile").value == "" ){

                    $("mobile").value = "+63";

                }

            }else{

                if($("mobile") && $("mobile").value != "" ){

                    $("mobile").value = "";

                }

            }           

        });       

        


        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');


        var updater = new jQuery.CityUpdater('country','region_id','city','<?php echo json_encode(Mage::helper('citydropdown')->getCities()); ?>','<?php echo $this->getFormData()->getCity() ; ?>','PH');        

        

        jQuery(document).ready(function($){

            $('#country').change(function(e){

                var streets = $('input[id=street_1]');

                if(streets.length > 0){

                    streets.each(function(i,elm){

                        $(elm).val(''); 

                    });

                } 

            }); 

            $('select#region_id').change(function(e){

                if($(this).val() == ""){

                    return ;

                }

                var streets = $('input[id=street_1]');

                if(streets.length > 0){

                    streets.each(function(i,elm){

                        $(elm).val(''); 

                    });

                } 

            });

        });

        

    //]]>

    </script>

</div>

<script>
jQuery('.numbersOnly').keyup(function () { 
    this.value = this.value.replace(/[^0-9+\.]/g,'');
});



</script>

<script type='text/javascript'>
    (function() {
        var f = function() {
              EF.init({ eventType: "transaction",
                        transactionProperties : "ev_Sign Up=1&ev_transid=<transid>",
                        segment : "27914", 
                        searchSegment : "",
                        sku : "",
                        userid : "940",
                        pixelHost : "pixel.everesttech.net"
                        
                        , allow3rdPartyPixels: 1});
              EF.main();
        };
        window.EF = window.EF || {}; 
        if (window.EF.main) {
            f();
            return;
        }
        window.EF.onloadCallbacks = window.EF.onloadCallbacks || [];
        window.EF.onloadCallbacks[window.EF.onloadCallbacks.length] = f;
        if (!window.EF.jsTagAdded) {
            var efjs = document.createElement('script'); efjs.type = 'text/javascript'; efjs.async = true;
            efjs.src = 'https://www.everestjs.net/static/st.v3.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(efjs, s);
            window.EF.jsTagAdded=1;
        }
    })();
</script>
<noscript><img src="https://pixel.everesttech.net/940/t?ev_Sign Up=1&ev_transid=<transid>" width="1" height="1"/></noscript>