<div class="page-title">
    <h2><?php echo $this->__('Quick Order - Return Policy') ?></h2>
	
   <p>
		In protecting the integrity of our products, and in consideration that they must follow strict storage conditions and various regulations, the following will be observed:
		<ul>
			<li>Return of items will be accepted on a case to case basis determined by our Quality Assurance Team.</li>

			<li>Items in good condition may be returned within three (3) working days upon receipt of the items.</li>

			<li> Clickhealth does not accept returns of the following items: a. Loose items (capsule, tablets, etc.), b. Injectables - vials, ampules, syringes, c. Biologicals and other refrigerated items - vaccines, insulins, etc.</li>

			<li>Customer must e-mail a copy of Official Receipt / Delivery Receipt to service@clickhealth.com.ph</li>

			<li>Returned items must be in the original sealed container, not damaged or adulterated.</li>

			<li>Refunds, net of any service fee, will be processed after receipt of the returned items in good condition.</li>
		
		</ul>
		
	</p>
</div>
