<div class="carousel_wrapper">
	<button class="prev button">&laquo;</button>
		<div class="homepage-banner-ads">
			<?php echo $this->getChildHtml("homepage-ads-content");?>
		</div>
	<button class="next button">&raquo;</button>
	<div class="clear"></div>
</div>
<script type="text/javascript">
// <![CDATA[ 
		jQuery(function($){
			$(".homepage-banner-ads").jCarouselLite({
				btnNext: ".next",
				btnPrev: ".prev",
				scroll: 1,
				auto: 5000,
				circular: true
			});
		}); 
// ]]></script>