<?php
	$root_id = Mage::app()->getStore()->getRootCategoryId(); //get selected stores root catalog
	$category_model = Mage::getModel('catalog/category'); //get category model       
	$root_category = $category_model->load($root_id);		
	$_categories = $root_category->getChildrenCategories();
?>

<?php if($_categories->count() > 0) : ?>
	
	<div id="category-list" class="category-list">
		<h3>Browse Our Categories</h3>
		<ul>
			
			<?php foreach($_categories as $category) : ?>
				
				<?php if($mCategory = Mage::getModel('catalog/category')->load($category->getId())) : ?>
					<?php if($_imgUrl = $mCategory->getListIcon()):?>
				
						<li>
							<a title="<?php echo $mCategory->getName()?>" href="<?php echo $mCategory->getUrl()?>"><img title="<?php echo $mCategory->getName()?>" src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$_imgUrl;?>" style="width:90px;height:90px;" alt="<?php echo $category->getName()?>"></a>
							<b style="display:block;"><a href="<?php echo $mCategory->getUrl()?>"><?php echo $mCategory->getName()?></a></b>
							<p style="margin:0px;" class="desc"><?php echo $this->htmlEscape($mCategory->getListTitle(),60)?></p>
						</li>
					<?php endif; ?>
				
				<?php endif; ?>
				
			<?php endforeach; ?>
			
		
		</ul> 
		<div class="clear">&nbsp;</div>
	</div>
	
<?php endif; ?>

