<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 5.0
 * @since        Class available since Release 5.0
 */
?>
<?php 
    $order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
    $quoteId = $order->getQuoteId();
    $quote = Mage::getModel('sales/quote')->load($quoteId );
    $paymentMethod = $quote->getPayment()->getMethodInstance()->getTitle();
    $shippingMethodDesc = $order->getShippingDescription();

    $orderDate = $order['created_at'];
    $orderDateFormat = new DateTime($orderDate);
    $orderDateFormat = $orderDateFormat->format('M j, Y');

    $shippingAddressId = $order['shipping_address_id'];
    $billingAddressId = $order['billing_address_id'];

    $addressShip = Mage::getModel('sales/order_address')->load($shippingAddressId);
    $custNameShip = $addressShip->getName();
    $custAddrShip = $addressShip->getStreetFull();
    $cityShip = $addressShip['city'];
    $regionShip = $addressShip->getRegion();
    $postcodeShip = $addressShip['postcode'];
    $countryShip = $addressShip->getCountry();
    $countryShip = Mage::getModel('directory/country')->loadByCode($countryShip);
    $countryShip = $countryShip->getName();
    $telNumShip = $addressShip['telephone'];
    $phoneNumShip = $addressShip['mobile'];

 
    $addressBil = Mage::getModel('sales/order_address')->load($billingAddressId);
    $custNameBil = $addressBil->getName();
    $custAddrBil = $addressBil->getStreetFull();
    $cityBil = $addressBil['city'];
    $regionBil = $addressBil->getRegion();
    $postcodeBil = $addressBil['postcode'];
    $countryBil = $addressBil->getCountry();
    $countryBil = Mage::getModel('directory/country')->loadByCode($countryBil);
    $countryBil = $countryBil->getName();
    $telNumBil = $addressBil['telephone'];
    $phoneNumBil = $addressBil['mobile'];

?>

<script>
    digitalData.page={ 
        pageInfo:{
            pageName:"ch:checkout:confirmation",
            site: "clickhealth"         
        },

        category:{        
            pageType:"Checkout",  
            primaryCategory: "Checkout",
            subCategory1: "Order Confirmation", 
            subCategory2: "",
            subCategory3: ""
        }

    }
</script>
<script>
    digitalData.transaction={
        purchaseID: "<?php echo $this->getOrderId(); ?>", 
        paymentMethodType: "<?php echo $order->getPayment()->getMethodInstance()->getTitle(); ?>",
        paymentMethodBrand: "",
        paymentStatus: "<?php echo $order->getStatusLabel();?>",
        totalOrderValue: "<?php echo $order->getGrandTotal();?>", 
        currency: "PHP",
        discount:
        {
            promoCode: "<?php echo $order->getCouponCode();?>",
            promoCodeDiscountAmt: "<?php echo $order->getDiscountAmount();?>",
        },
        deliveryState: "<?php echo $order->getShippingAddress()->getRegion();?>",
        deliveryCity: "<?php echo $order->getShippingAddress()->getCity();?>",
        zipCode: "<?php echo $order->getShippingAddress()->getPostcode();?>",
    
        item:[

            <?php foreach ($order->getAllItems() as $item) :
                $product2 = Mage::getModel('catalog/product')->load($item->getProductId()); 
        $brand = $product2->getUnilabBrand();
        $size = $product2->getUnilabSize();

        $unilab_brand_text = Mage::getModel('admincontroller/convertattrib')->idtotext($item->getProductId(), $brand, 'unilab_brand');
        $unilab_size_text = Mage::getModel('admincontroller/convertattrib')->idtotext($item->getProductId(), $size, 'unilab_size');
        
            ?>  
            { 
                quantity:"<?php echo $item->getqty_ordered();?>",
                price: {
                    basePrice: "<?php echo $item->getbase_price(); ?>" 
                       },
                    productInfo:{               
                    productID: "<?php echo $product2->getSku();?>",
                    productName: "<?php echo $product2->getName();?>",
                    productBrand: "<?php echo $unilab_brand_text;?>",
                    productSize: "<?php echo $unilab_size_text;?>"
                    
                      }
            },
            <?php endforeach; ?>
        ]
    } 
    digitalData.events = "purchase";
</script>

<div class="page-title">
    <h1><?php echo $this->__('Thank you, your order has been placed.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title" style="display:none;"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<div class="header-desc">
    You will receive email and SMS confirmation for this order. For cash on delivery payment, please 
    reply to the email or SMS to confirm delivery details. Your tracking number will be sent after confirmation.
</div>



<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <div class="order-num"><?php echo $this->__('Order# %s', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></div>
<?php  else :?>
    <div class="order-num"><?php echo $this->__('Order# %s', $this->escapeHtml($this->getOrderId())) ?></div>
<?php endif;?>
    <div class="order-date"> 
        Order Date
        <span><?php echo $orderDateFormat;?></span>
    </div>

    <p><?php/** echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') */?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php /* echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) */?>        
    </p>
<?php endif;?>


<div class="address-preview">
    <span class="address-shipping-container">Shipping details</span>
    <div class="address-preview-shipping">
        <ul>
            <li>
                <span class="inner-label-ship">
                    <h3>Shipping address</h3>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $custNameShip;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $custAddrShip;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $cityShip;?> . <?php echo $regionShip;?> . <?php echo $postcodeShip;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $countryShip;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $telNumShip;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $phoneNumShip;?>
                </span>
            </li>
            <li>
                <div class="ship-method-label">
                    Shipping method
                </div>
                <div class="ship-method">
                    <?php echo $shippingMethodDesc;?>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="address-preview" id="billing-container">
    <span class="address-billing-container">Payment information</span>
    <div class="address-preview-billing">
        <ul>
            <li>
                <span class="inner-label-bill">
                    <h3>Billing address</h3>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $custNameBil;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $custAddrBil;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $cityBil;?> . <?php echo $regionBil;?> . <?php echo $postcodeBil;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $countryBil;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $telNumBil;?>
                </span>
            </li>
            <li>
                <span>
                    <?php echo $phoneNumBil;?>
                </span>
            </li>
            <li>
                <div class="pay-method-label">
                    Payment method
                </div>
                <div class="pay-method">
                    <?php echo $paymentMethod;?>
                </div>
            </li>
        </ul>
    </div>
</div>    

<?php echo $this->getChildHtml() ?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>

<script type='text/javascript'>
    (function() {
        var f = function() {
              EF.init({ eventType: "transaction",
                        transactionProperties : "ev_Thank You Page_Order=1&ev_revenue=<rev>&ev_transid=<transid>",
                        segment : "27954", 
                        searchSegment : "",
                        sku : "",
                        userid : "940",
                        pixelHost : "pixel.everesttech.net"
                        
                        , allow3rdPartyPixels: 1});
              EF.main();
        };
        window.EF = window.EF || {}; 
        if (window.EF.main) {
            f();
            return;
        }
        window.EF.onloadCallbacks = window.EF.onloadCallbacks || [];
        window.EF.onloadCallbacks[window.EF.onloadCallbacks.length] = f;
        if (!window.EF.jsTagAdded) {
            var efjs = document.createElement('script'); efjs.type = 'text/javascript'; efjs.async = true;
            efjs.src = 'https://www.everestjs.net/static/st.v3.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(efjs, s);
            window.EF.jsTagAdded=1;
        }
    })();
</script>
<noscript><img src="https://pixel.everesttech.net/940/t?ev_Thank You Page_Order=1&ev_revenue=<rev>&ev_transid=<transid>" width="1" height="1"/></noscript>