<?php   

$OrderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
   
$pagetitle = "Failed";

$order = Mage::getModel('sales/order')->loadByIncrementId($OrderId);

?>
<script>
    digitalData.page={ 
        pageInfo:{
            pageName:"ch:checkout:payment failed",
            site: "clickhealth"         
        },
        category:{        
            pageType:"Checkout", 
            primaryCategory: "Checkout", 
            subCategory1: "Order Failure", 
            subCategory2: "",
            subCategory3: ""
        }
    }
</script>
<script>
	digitalData.transaction={
		purchaseID: "<?php echo $OrderId; ?>", 
		paymentMethodType: "<?php echo $order->getPayment()->getMethodInstance()->getTitle(); ?>",
		paymentMethodBrand: "",
		paymentStatus: "Failed",
		totalOrderValue: "<?php echo $order->getGrandTotal()?>", 
		currency: "PHP",
		discount:
		{
			promoCode: "<?php echo $order->getCouponCode();?>",
			promoCodeDiscountAmt: "<?php echo $order->getDiscountAmount();?>",
		},
		deliveryState: "<?php echo $order->getShippingAddress()->getRegion();?>",
		deliveryCity: "<?php echo $order->getShippingAddress()->getCity();?>",
		zipCode: "<?php echo $order->getShippingAddress()->getPostcode();?>",
	
		item:[

			<?php foreach ($order->getAllItems() as $item) :
				$product2 	= Mage::getModel('catalog/product')->load($item->getProductId());	
				$brand 		= $product2->getUnilabBrand();
				$size 		= $product2->getUnilabSize();

				$unilab_brand_text = Mage::getModel('admincontroller/convertattrib')->idtotext($item->getProductId(), $brand, 'unilab_brand');
				$unilab_size_text = Mage::getModel('admincontroller/convertattrib')->idtotext($item->getProductId(), $size, 'unilab_size');
			?>	
			{ 
				quantity:"<?php echo $item->getqty_ordered();?>",
				price: {
					basePrice: "<?php echo $item->getbase_price(); ?>"
					   },
				productInfo:{ 				
					productID: "<?php echo $product2->getSku();?>",
					productName: "<?php echo $product2->getName();?>",
					productBrand: "<?php echo $unilab_brand_text;?>",
					productSize: "<?php echo $unilab_size_text;?>"
					
					  }
			},
			<?php endforeach; ?>
		]
	} 
	digitalData.events = "purchase";
	
	
</script>

<div class="page-title">
    <h1><?php echo $this->__('Payment Transaction Failed') ?></h1>
</div>
<div class="checkout-success">
    
    <p><b><?php echo $this->__('Your transaction with BPI Securepay has failed.')?></b></p>
   
	<p><b><?php echo $this->__('You may click on <a href="'.Mage::getUrl('customer/account').'">'.$this->__('My Account').'</a> to view details of your order.</span>')?></b></p>
	
    <div class="buttons-set">
        <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo Mage::getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    </div>
</div>