<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>"> <!--<![endif]-->
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page layout-grid">
        <?php echo $this->getChildHtml('header') ?>


        <div class="row">

            <div class="main-container col2-left-layout">			
                <div class="up_border">			
                </div>
                <div class="main">
                    <?php echo $this->getChildHtml('breadcrumbs') ?>

                    <div class="col-left sidebar-top">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Operated_by')->toHtml(); ?>  
                        <?php echo $this->getChildHtml('left') ?>
                    </div>

                    <div class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shopbycategory')->toHtml(); ?>
                    </div>
                    <div class="col-left sidebar-bottom"><?php echo $this->getChildHtml('left') ?></div>

                </div>			
                <div class="down_border">			
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
    </div>
    <!-- Loading Icon -->
	<div id="loading-icon">
	    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/default/unilab2/images/loading-icon.gif">
	</div>
	<!-- The Modal -->
	<div id="myModal" class="modal">
	  <!-- Modal content -->
	  <div class="modal-content">
	    <div class="modal-header">
	      <h2>Work-Place</h2>
	    </div>
	    <div class="modal-body">
	      <p><span id="prodName"></span> was added to your shopping cart</p>
	    </div>
	    <div class="modal-footer">
	      <button type="button"title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-cshopping"><span><?php echo $this->__('Continue Shopping') ?></span></button>
	      <button type="button" returnUrl="<?php echo Mage::helper('checkout/url')->getCartUrl() ?>" title="<?php echo $this->__('Proceed to Cart') ?>" class="button btn-checkout" ><span><?php echo $this->__('Proceed to Cart') ?></span></button>
	    </div>
	  </div>
	</div>
	</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
<script> 
var ums<?php echo rand(22,4444);?> = UnilabAccord.init({
												headerclass: "expandable2",
												contentclass: "categoryitems2",
												revealtype: "clickForce", 
												mouseoverdelay: 200, 
												collapseprev: true, 
												defaultexpanded: [], 
												onemustopen: false, 
												animatedefault: false, 
												persiststate: false,  
												toggleclass: ["", "openheader"], 
												togglehtml: ["prefix", "", ""],  
												animatespeed: "fast",  
												oninit:function(headers, expandedindices){},
												onopenclose:function(header, index, state, isuseractivated){}
											}) 


	var ums<?php echo rand(22,4444);?> = UnilabAccord.init({
												headerclass: "expandable",
												contentclass: "categoryitems",
												revealtype: "clickForce", 
												mouseoverdelay: 200, 
												collapseprev: true, 
												defaultexpanded: [], 
												onemustopen: false, 
												animatedefault: false, 
												persiststate: false,  
												toggleclass: ["", "openheader"], 
												togglehtml: ["prefix", "", ""],  
												animatespeed: "fast",  
												oninit:function(headers, expandedindices){},
												onopenclose:function(header, index, state, isuseractivated){}
											})  
</script>
<script type="text/javascript">
   jQuery(document).on('click','.add-btn',function(){
        jQuery("#loading-icon").show();
        var product = jQuery(this).attr('returnId');
        var productName = jQuery(this).attr('returnName');
        jQuery.ajax({
        type: 'Post',
        url:'<?php echo Mage::getBaseUrl()?>checkout/cart/addtoCart',
        data: {
            product: product
        },
        }).done(function(data){
            jQuery("#prodName").html(productName);    
            jQuery("#loading-icon").hide(); 
            jQuery("#myModal").show();
        });
    });

   jQuery(document).on('click','.close',function(){
        jQuery("#myModal").hide();
    });

    jQuery(document).on('click','.btn-cshopping',function(){
        location.reload();
    });

    jQuery(document).on('click','.btn-checkout',function(){
        window.location = jQuery(this).attr('returnUrl');

    });
   
</script>
</html>
