<!--div class="inquiry_wrapper">

	<div class="inquiry_wrapper1">
		<div class="inquiry-type-wrapper">
			<p><?php echo $this->__("Good Day! I'm a Doctor");?></p>
			<p><?php echo $this->__("<b>Not Feeling Well?</b>");?></p>
			<p><?php echo $this->__("Send us an email and we'll get back to you!");?></p>
			<a href="<?php echo $this->getUrl("inquiry/index/showform", array('code' => $this->getHashDepartmentCode('DOCTOR'))); ?>" class="email-link fancybox.ajax button">Email Us</a> 
		</div>
	</div>
	
	
	<div class="inquiry_wrapper2">
		<div class="inquiry-type-wrapper _right">
			<p><?php echo $this->__("Hello! I'm a Pharmacist");?></p>
			<p><?php echo $this->__("<b>Don't know what medicine to take?</b>");?></p>
			<p><?php echo $this->__("Send us an email and we'll get back to you!");?></p>
			<a href="<?php echo $this->getUrl("inquiry/index/showform", array('code' => $this->getHashDepartmentCode('PHARMACIST'))); ?>" class="email-link fancybox.ajax button">Email Us</a>
		</div>
	</div>

</div--><div class="home-banner">	<img src="<?php echo $this->getSkinUrl();?>images/banner-homepage.jpg" width="100%"></div>

<script type="text/javascript">
  jQuery(function($){
    $('.email-link').fancybox({closeBtn: false,
								 closeClick: false,
								 helpers: { overlay : {closeClick : false,
													  locked:	   true}}});
  });
</script>