<?php     
    $transferstockId = $this->getRequest()->getParam('id');
    $can_transfer = Mage::helper('inventory/stocktransfering')->checkEditStocktransfering($transferstockId);
    $status = Mage::getModel('inventory/stocktransfering')->load($this->getRequest()->getParam('id'))->getStatus();
    $editable = false;
    if ($can_transfer == 1 && $status == 2)
        $editable = true;
    $showImport = true;   
    if ($this->getRequest()->getParam('id')) {
        if(($status != 1 && $status != 2) || !$can_transfer || $can_transfer != 1){
            $showImport = false;
        }
    }
?>
<?php if($showImport): ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Import Products By Csv file') ?></h4>
        </div>
        <div id="stocktransfering_form" class="fieldset ">
            <div style="float: left;">
                <div>
                    <label for="fileToUpload">
                            <?php echo $this->__('Please choose CSV file to import') ?>
                    </label><br />
                    <input type="file" name="fileToUpload[]" id="fileToUpload" onchange="fileSelected();" enctype="multipart/form-data"/>
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" id="form_key"/>
                    <button style="" onclick="uploadFile()" class="scalable task" type="button" id="Upload"><span><?php echo $this->__('Import') ?></span></button>
                </div>
                <!--<div style="float:right;">
                    <a href="<?php echo Mage::getBaseUrl('media').'inventory/csv/import_product_to_transferstock.csv';?>"><?php echo $this->__('Example File') ?></a>
                </div>-->
                <div class="clear"></div>
                <div id="fileName">
                </div>
                <div id="fileSize">
                </div>
                <div id="fileType">
                </div>
                <div id="progressNumber">
                </div>
            </div>
            <div id="messages" style="float: left;padding-left: 20px;width:60%;">
                <ul class="messages">
                    <li class="notice-msg">
                        <ul>
                            <?php if(!$status): ?>
                                <li>
                                    <?php echo $this->__('When you want to Create Stock Transfering, the structure of CSV file is as follows: <h1><b>SKU,QTY_REQUEST</b></h1>') ?>                             
                                    <?php $example = "SKU : SKU of product <br />" ?>                               
                                    <?php $example .= "QTY_REQUEST : QTY Request of product to Create Stock Transfering" ?>                                                               
                                    <div style="padding-left: 20px;" ?>
                                        <?php echo $example ?>
                                    </div>
                                </li>
                                <li>
                                    <div style="float:left;">                                    
                                        <b><?php echo $this->__('Example file') ?><a href="<?php echo Mage::getBaseUrl('media').'inventory/csv/import_product_request_to_transferstock.csv';?>">(<?php echo $this->__('Download') ?>)</a></b>
                                    </div>
                                </li>
                            <?php elseif($status == 1): ?>
                                <li>
                                    <?php echo $this->__('When you want to Create Stock Transfering, the structure of CSV file is as follows: <h1><b>SKU,QTY_TRANSFER</b></h1>') ?>                             
                                    <?php $example = "SKU : SKU of product <br />" ?>                               
                                    <?php $example .= "QTY_TRANSFER : QTY Transfer of product to Create Stock Transfering" ?>                                                               
                                    <div style="padding-left: 20px;" ?>
                                        <?php echo $example ?>
                                    </div>
                                </li>
                                <li>
                                    <div style="float:left;">                                    
                                        <b><?php echo $this->__('Example file') ?><a href="<?php echo Mage::getBaseUrl('media').'inventory/csv/import_product_transfer_to_transferstock.csv';?>">(<?php echo $this->__('Download') ?>)</a></b>
                                    </div>
                                </li>
                            <?php else: ?>
                                <li>
                                    <?php echo $this->__('When you want to Create Stock Transfering, the structure of CSV file is as follows: <h1><b>SKU,QTY_RECEIVE</b></h1>') ?>                             
                                    <?php $example = "SKU : SKU of product <br />" ?>                               
                                    <?php $example .= "QTY_RECEIVE : QTY Receive of product to Create Stock Transfering" ?>                                                               
                                    <div style="padding-left: 20px;" ?>
                                        <?php echo $example ?>
                                    </div>
                                </li>
                                <li>
                                    <div style="float:left;">                                    
                                        <b><?php echo $this->__('Example file') ?><a href="<?php echo Mage::getBaseUrl('media').'inventory/csv/import_product_receive_to_transferstock.csv';?>">(<?php echo $this->__('Download') ?>)</a></b>
                                    </div>
                                </li>
                            <?php endif ?>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>
<?php endif ?>