<div id="cancelPrescriptionTransaction"> 
	<h3><?php echo $this->__("Are you sure you want to cancel this transaction?");?></h3> 
	<p style="text-align: center;margin: 0 auto;width: 224px;">	
		<input type="button" name="close" class="button" id="btnCancelPrescriptionTransaction" value="<?php echo $this->__("Yes");?>"/>
		<input type="button" name="close" class="button" id="btnCancelPrescriptionCancelTransaction" value="<?php echo $this->__("No");?>"/>
	</p>
</div>   