<?php 

/**
	-> Celeteque International Shipping
	
	-> Author 	: Richel R. Amante
	
	-> Email	: richelramante@gmail.compile
	
	-> Date		: October 29, 2014
	
	-> Filename	: layout.phtml	
	
**/

?>

<!--Popup Style-->

<style>	


		.form-wrapper
		{
			text-align: center;
		}
		.waiver-wrapper
		{
			position: fixed;
			top: -400px;
			z-index: 999999;
			width: 50%;
			left: 25%;
			background-color: white;
			padding: 20px;
			border-radius: 10px;
			display:none;
		}
		
		.waiver-wrapper2
		{
			display:none;
			position: fixed;
			top: 25%;
			width:35%;
			z-index: 999999;
			left: 32.5%;
			background-color: white;
			padding: 20px;
			border-radius: 10px;
		}
		
		
		.waiver-wrapper p
		{
			line-height:20px;
			font-size:16px;
		}
		.background-black
		{
			position: fixed;
			width:100%;
			height:100%;
			height:100vh;
			min-height:800px;
			background-color:#000;
			opacity:.7;
			z-index: 999998;
			display:none;
			top: 0px;
			left: 0px;
			
		}
		
		.input-wrapper input[type=checkbox]
		{
			display: inline-block;
			margin: 10px 10px 10px 0px;
			width: 20px;
			height: 20px;
		}
		
		.input-wrapper label {
			position: relative;
			top: 0px;
			left: -5px;
			font-size: 16px;
			font-weight: bold;
		}
		
		.waiver-content
		{
			max-height:400px;
			overflow:auto;
		}
		
		#other-message
		{
			display:none;
		}
		.address-wrapper
		{
			position: absolute;
			top: 0px;
			background-color: #ccc;
			width: 100%;
			left: 0px;
			margin-bottom: 10px;
			border-radius: 10px 10px 0px 0px;
			max-height: 60px;
		}
		.address-wrapper p{
			padding: 0px 20px 0px 20px;
			width: 93%;
			text-overflow: ellipsis;
			overflow: hidden;
			max-height: 40px;
		}
		.close_waiver
		{
			float: right;
			border: 1px solid #000;
			border-radius: 13px;
			padding: 0px 5px 0px 5px;
			position: relative;
			right: -18px;
			cursor: pointer;
		}
		
</style>


<!--Begin of notice-->

<div class="background-black"></div>

<div class="waiver-wrapper">	
	<div class="waiver-content">		
		<h5 class="address-wrapper">
			<p class="heade_content">
			</p>
		</h5>		
		<div class="waiver-title">
			<h2 class="waiver-title-data">
			</h2>
		</div>
		
		<div class="waiver-content-data">
		</div>									
	</div>
	<div class="form-wrapper">
		<button type="button" title="Save" class="button" onclick="save_agree()" id="save_data"><span><span>I Agree</span></span></button>
		<button type="button" title="Cancel" class="button" onclick="cancel_agree()"><span><span>I Disagree</span></span></button>
	</div>
</div>

<div class="waiver-wrapper2" id="other-message">
	<div>
		<h3 class="waiver-other-data">
		</h3>		
		<div class="form-wrapper">		
			<button type="button" title="ok" class="button" onclick="ok_button();"><span><span>OK</span></span></button>			
		</div>	
	</div>	
</div>

<!--End of notice-->


<script>
			
		function show_waiver()
		{
				
				
				jQuery.post('<?php echo Mage::getBaseUrl(); ?>celeteque/Index/waiver',{
				
					ordernumber: 'getdata',
				
				},
				
				function (data) {
				
					var get_data = jQuery.parseJSON(data);
					
					if  (get_data.success == true)
					{
						if ((get_data.waiver_active == 1) && (get_data.country_code != get_data.waiver_code))
						{
							//jQuery('.heade_content').html(get_data.heade_content);
							
							jQuery('.waiver-title-data').html(get_data.waiver_title);
							
							jQuery('.waiver-content-data').html(get_data.waiver_content);
							
							jQuery('.waiver-other-data').html(get_data.waiver_other);		

							jQuery('#save_data').attr('order-data',get_data.order_number);											

							jQuery('#save_data').attr('user-data',get_data.userid);	
							
							jQuery('.background-black').fadeIn();						
							
							jQuery('.waiver-wrapper').fadeIn();
							
							jQuery('.waiver-wrapper').animate({top:"10%"});
							

						}
						else{
						
							jQuery('#submit-btn').click();
							
						}
					}
					else{
						alert('Error and get data from database');
					}
				
				});		
		}
		
		function cancel_agree()
		{
			
			jQuery('.waiver-wrapper').animate({top:"-400px"});

			jQuery('.waiver-wrapper').fadeOut();
			
			jQuery('#other-message').fadeIn();
		}

		
		function ok_button()
		{
			jQuery('#other-message').fadeOut();
			jQuery('.background-black').fadeOut();
		}
		
		jQuery('body').on('click', '.close_waiver', function (){
		
			cancel_agree();
			
			
		});
		
		function save_agree()
		{					
				
			jQuery('.waiver-wrapper').fadeOut();
			
			jQuery('#other-message').fadeOut();
			
			jQuery('.background-black').fadeOut();
			
			jQuery('#submit-btn').click();
			
		}
</script>