<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li><a href="http://www.dragonpay.ph/" target="_blank"><img src="<?php echo $this->getSkinUrl('images/payment/dragonpay-logo.jpg')?>"/></a></li>
	<!--
	<li>
		<div id="online-banking" class="banks">
			<div>
				<h2 style="font-size:11px;">Online Banking</h2>				
				<ul style="margin:0px">
					<li>Banco de Oro (BDO)</li>
					<li>Bank of the Philippine Islands (BPI)</li>
					<li>Metrobank</li>
					<li>Rizal Commercial Banking Corp (RCBC)</li>
					<li>Unionbank</li>
					<li>United Coconut Planters Bank (UCPB)</li>
					<li>Chinabank</li>
					<li>Philippine National Bank (PNB)</li>
					<li>Maybank</li>
					<li>Robinsons Bank</li>
					<li>Sterling Bank of Asia</li>
					<li>EastWest Bank (EWB)</li>
				</ul>
			</div>			
		</div>

		<div id="counter-banking" class="banks">
			<div>
				<h2 style="font-size:11px;">Over the counter Banking</h2>
				<ul style="margin:0px">
					<li>Banco de Oro (BDO)</li>
					<li>Bank of the Philippine Islands (BPI)</li>
					<li>Metrobank</li>
					<li>Rizal Commercial Banking Corp (RCBC)</li>
					<li>Chinabank</li>
					<li>EastWest Bank (EWB)</li>
					<li>Landbank</li>
					<li>Maybank</li>
					<li>Philippine National Bank (PNB)</li>
					<li>Robinsons Bank</li>
					<li>Security Bank</li>
					<li>Sterling Bank of Asia</li>
					<li>United Coconut Planters Bank (UCPB)</li>
					<li>Unionbank</li>
				</ul>
			</div>
		</div>

		<div id="counter-nonbank" class="banks">
			<div>
				<h2 style="font-size:11px;">Over the counter Non-Bank</h2>
				<ul style="margin:0px">
					<li>LBC</li>
					<li>SM Payment Counters</li>
					<li>M.Lhuillier branches</li>
				</ul>
			</div>
		</div>

	</li>
	-->
	
    <li><?php echo $this->__('You will be redirected to the DragonPay website when you place an order.') ?></li>
</ul>