<?php 
$payment_method_code = Mage::getSingleton('checkout/session')->getQuote()->getPayment()->getMethodInstance()->getCode();
?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="margin: 0 auto;">
    <thead>
    <tr>
        <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Payment Method:</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td valign="top" align="left" style="font-size:12px; padding:7px 9px 9px 9px; border-left:1px solid #EAEAEA; border-bottom:1px solid #EAEAEA; border-right:1px solid #EAEAEA;">
            <?php if($payment_method_code == "perapal"): ?>
                <p>You have chosen Cebuana Lhuiller as your mode of payment</p>
            <?php elseif($payment_method_code == "cashondelivery"): ?>
                <p>You have chosen Cash on Delivery (COD) as your mode of payment</p>
                <p>Please be ready with the exact amount to be paid to our courier upon delivery.</p>
            <?php endif; ?>
        </td>
    </tr>
    </tbody>
</table>