<?php

// This page is create by Richel R. Amante for UNILAB use only.
// Please do not used this software or take with your own risk.
// Thank you!!!

?>
<?php
	$this->getshipppingAddress(); 
	$this->getsetting();
	$this->getpaymentmethod();
	$this->getsubtotalincltax();
	$this->getdefualtAddress();
	$this->getaAmountdata();
	$this->loadAddress();
	
	echo $this->getChildHtml('style_css'); 
	
	$customername = Mage::getSingleton('customer/session')->getcustomer()->getfirstname();
	$methodcode = Mage::getSingleton('core/session')->getPaymentMethod(); 
	$storeId = Mage::app()->getStore()->getStoreId();

?>

<!-- <div class="container_wapper">

</div> -->

<div class="shipping-address">
	<?php echo $this->getChildHtml('shipping_address'); ?>	
</div>


<div class="shipping-method">
	<?php echo $this->getChildHtml('shipping_method'); ?>
</div>

<div class="payment-method">
	<?php echo $this->getChildHtml('payment_method'); ?>
	<?php echo $this->getChildHtml('payment_instructions'); ?>
</div>

<div class="billing-address">
	<?php echo $this->getChildHtml('billing_address'); ?>	
</div>

<div class="checkout-nav">
	<input type="button" value="Continue" class="checkout-paging"/>
</div>


<div class="orderview-wrapper">
	<div class="checkout-items">
		<?php 	echo $this->getChildHtml('items'); ?>
	</div>
	<div class="checkout-totals">
		<?php echo $this->getChildHtml('totals'); ?>
	</div>
	<div class="checkout-placeorder">
		<?php echo $this->getChildHtml('place_order'); ?>
	</div>
</div>


<script type="text/javascript">

	jQuery(document).ready(function (){	

		var paymentname = jQuery("#paymentmethod").val();

		if(paymentname != 'bankdeposit'){
			jQuery("#payment_instruction_bankdeposit").css({ display: "none" });
		}else{
			jQuery("#payment_instruction_bankdeposit").css({ display: "block" });
		}	
		
		if(paymentname != 'perapal'){
			jQuery("#payment_instruction_cebuana").css({ display: "none" });
		}else{
			jQuery("#payment_instruction_cebuana").css({ display: "block" });
		}
	});

	//BILLING ADDRESS
	jQuery('.numbersOnly').keyup(function () { 
		this.value = this.value.replace(/[^\d].+/, "");
	});
	

	jQuery('#billing_save_in_address_book_yes').click(function(){

		if(confirm('Do you want to save your billing address?')){
			jQuery("#billing_save_in_address_book").click();
			jQuery("#billing_save_in_address_book").val(1);
		}

	});


	function check2(state_id,city_id)
	{		
	
		var array_state ='<?php $stateprovince2 = Mage::getStoreConfig('payment/cashondelivery/stateprovince');
							$default_state = '';
							$stateprovince2 = explode(',', $stateprovince2);

							foreach($stateprovince2 as $stateprovince){
								$default_state .= $stateprovince .","; 
							} 
							echo substr($default_state,0,-1); ?>';



		var array_city ='<?php $city2 = Mage::getStoreConfig('payment/cashondelivery/city');
							$default_city = ''; 
							$city2 = explode(',', $city2);
							foreach($city2 as $city){ 
									$default_city .= $city .","; } 
							echo substr($default_city,0,-1); ?>';

   	
		var splitObj = array_state.split(","); 
		var splitObj2 = array_city.split(",");
		

		if(jQuery.inArray(state_id, splitObj) !=-1 && jQuery.inArray(city_id, splitObj2) !=-1){
			jQuery('#cashondelivery').attr('disabled', false);
			jQuery("label[for='p_method_cashondelivery']").attr('disabled', false);

		}else{
			jQuery('#cashondelivery').attr('disabled', true);
			jQuery('#cashondelivery').removeAttr("checked");
			jQuery("#cashondelivery_name").css('display', 'none');

		}
	}

	function address(){
		var bill_fname = jQuery('#billing_firstname').val();
			jQuery('#shipping_firstname').val(bill_fname);

			var bill_lname = jQuery('#billing_lastname').val();
			jQuery('#shipping_lastname').val(bill_lname);

			var bill_country = jQuery('#billing_country_id').val();
			jQuery('#shipping_country_id').val(bill_country);

			var bill_postcode = jQuery('#billing_postcode').val();
			jQuery('#shipping_postcode').val(bill_postcode);

			var billing_region = jQuery('#billing_region_id').val();
			jQuery('#shipping_region_id').val(billing_region);

			var bill_city = jQuery('#billing_city').val();
			jQuery('#shipping_city').val(bill_city);
			
			var bill_street = jQuery('#billing_street1').val();
			jQuery('#shipping_street1').val(bill_street);

			var bill_tel = jQuery('#billing_telephone').val();
			jQuery('#shipping_telephone').val(bill_tel);

			var bill_mobile = jQuery('#billing_mobile').val();
			jQuery('#shipping_mobile').val(bill_mobile);
	}
	
	jQuery('.billing_address_id').click(function () {
			var addressid = jQuery(this).val();
			selectAddress_billing(addressid);
		});


	function selectAddress_billing(addressid)
	{
	
		var addID = addressid; //jQuery('#billing_address_id').val();		

		jQuery.post( '<?php echo Mage::getBaseUrl();?>rracheckout/address/addressbill',{ 
			addressID: addID
			},
			function (addressData)
			{
			var dataobj = jQuery.parseJSON(addressData)
			if (dataobj.success == true)
			{
				jQuery('#billingAddressId').val(addressid);
				jQuery('#billing_tin').val(dataobj.tin);
				jQuery('#billing_firstname').val(dataobj.firstname);
				jQuery('#billing_lastname').val(dataobj.lastname);
				
				jQuery('#billing_country_id').val(dataobj.country_id);
				jQuery('#billing_postcode').val(dataobj.postcode);				

				jQuery('#billing_telephone').val(dataobj.telephone);
				jQuery('#billing_mobile').val(dataobj.mobile);
				jQuery('#billing_street1').val(dataobj.street);
				
				jQuery('#billing_region_id').val(dataobj.region_id);
				jQuery('#billing_region').val(dataobj.region);

				jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/webuiltthiscity', {region_id: dataobj.region_id, cityval: dataobj.city}, function(res){				
					jQuery("#billing_city").html(res);
				});

				jQuery('#billing_city').val(dataobj.city);

				if(document.getElementById('billing_use_for_shipping_yes').checked) {
					check2(dataobj.region_id, dataobj.city);

					address();
					jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: dataobj.region_id, city_id: dataobj.city}, function(res){			
						jQuery("#shipping_city").html(res);
					});

					setTimeout(function(){
						jQuery('input[name=shippingmethod').prop('checked', true).trigger('click');
				
					}, 2000);
				}
				
				
				var paymentdata = jQuery("#billing_address_form").serialize();
				
				jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveBilling/', 
			
					paymentdata,

				function (paymentdataret)
				{
					var dataobj = jQuery.parseJSON(paymentdataret);
					
					if(dataobj.success == true)
					{
						jQuery('#amt_'+dataobj.carrier_code+'').html(dataobj.carrier_method_title + ' - ' + dataobj.shippingrate);
						jQuery('.shipping_name').html(dataobj.carrier_title + ' - ' + dataobj.carrier_method_title);
						jQuery('.shipping_amount').html(dataobj.shippingrate);
						jQuery('.grand_total').html(dataobj.grandTotal);
						jQuery('.tax_amount').html(dataobj.taxAmount);					
						jQuery('#submit_btn').removeAttr('disabled');


					}
					else
					{
						
					}

				});	
				
			}else{

				jQuery('#billing_firstname').val('');
				jQuery('#billing_lastname').val('');
				
				jQuery('#billing_postcode').val('');				
				
				jQuery('#billing_city').val('');
				jQuery('#billing_telephone').val('');
				jQuery('#billing_mobile').val('');
				jQuery('#billing_street1').val('');
				
				jQuery('#billing_region_id').val('');
				jQuery('#billing_region').val('');
				jQuery('#billing_siab').show();

			}
		});
	}

	function onchangeAddressSave()
	{
		
		jQuery("#billing_save_in_address_book").attr('checked', 'checked');
		jQuery("#billing_save_in_address_book").val(1);

	} 

	function changeAddressMode(e)
	{
		if(e == true)
		{
			jQuery('#billing_use_for_shipping_yes').val(1);

			jQuery('.shipping_address').hide();
		}
		else{
			jQuery('#billing_use_for_shipping_yes').val(0);
			jQuery('.shipping_address').show();

				jQuery('#shipping_address_form').change(function () {

					// var paymentdata = jQuery("#billing_address_form").serialize();
					var shippingdata = jQuery("#shipping_address_form").serialize();

						jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/savenewShipping/', 
							shippingdata,

						function (paymentdataretshippingaddress)
						{

						});
				});
		}
	}
	

	jQuery(".save_address_book").click(function (){
		var check = confirm("Do you want to save your new address?");
		if (check == true) {
			jQuery('#billing_save_in_address_book').prop('checked', true);
		}
	});

	jQuery(".ship_address").click(function (){
		if(document.getElementById('billing_use_for_shipping_yes').checked) {
			jQuery('#billing_use_for_shipping_yes').prop('checked', false);
			jQuery('.shipping_address').show();
			jQuery('.ship_address').html('Ship to this address');
		} else {
			jQuery('#billing_use_for_shipping_yes').prop('checked', true);
			jQuery('.shipping_address').hide();
			jQuery('.ship_address').html('Ship to different address');

			var bill_fname = jQuery('#billing_firstname').val();
			jQuery('#shipping_firstname').val(bill_fname);

			var bill_lname = jQuery('#billing_lastname').val();
			jQuery('#shipping_lastname').val(bill_lname);

			var bill_country = jQuery('#billing_country_id').val();
			jQuery('#shipping_country_id').val(bill_country);

			var bill_postcode = jQuery('#billing_postcode').val();
			jQuery('#shipping_postcode').val(bill_postcode);

			var billing_region = jQuery('#billing_region_id').val();
			jQuery('#shipping_region_id').val(billing_region);

			var bill_city = jQuery('#billing_city').val();
			jQuery('#shipping_city').val(bill_city);

			jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: billing_region, city_id: bill_city}, function(res){			
				jQuery("#shipping_city").html(res);
			});
			
			var bill_street = jQuery('#billing_street1').val();
			jQuery('#shipping_street1').val(bill_street);

			var bill_tel = jQuery('#billing_telephone').val();
			jQuery('#shipping_telephone').val(bill_tel);

			var bill_mobile = jQuery('#billing_mobile').val();
			jQuery('#shipping_mobile').val(bill_mobile);

			setTimeout(function(){
				jQuery('input[name=shippingmethod').prop('checked', true).trigger('click');
			
			}, 2000);

		
			check2(billing_region, bill_city);

		}
	});

	jQuery('#billing_save_in_address_book').change(function () {
		if(jQuery('#billing_save_in_address_book').is(':checked')){
		jQuery("#billing_save_in_address_book").val(1);

			var shippingaddressdata = jQuery('#billing_address_form').serialize();
			jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveanotherBilling/', 
				shippingaddressdata,

				function (shipdataretship)
				{
					var dataobj = jQuery.parseJSON(shipdataretship);

					if (dataobj.reload == true)
					{
									
							jQuery("#shippingmethod").click();
										
					}else{

						return;
					}	
				}
			);


		}else{
			jQuery("#billing_save_in_address_book").val(0);
		}

		jQuery("#billing_save_in_address_book").val(1);

	 });


	function onchangeBillingSave() //selecting city
	{
		var paymentdata = jQuery('#billing_address_form').serialize();
		
		jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/savenewBilling/', 
		
		paymentdata,

		function (paymentdataretship)
		{

			var dataobj = jQuery.parseJSON(paymentdataretship);

			if (dataobj.reload == true)
			{
			
				jQuery("#shippingmethod").click();
			
			}else{

				return;
			}

		});	

	}



	jQuery('#billing_firstname').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_fname = jQuery('#billing_firstname').val();
			jQuery('#shipping_firstname').val(bill_fname);
		}
	});

	jQuery('#billing_lastname').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_lname = jQuery('#billing_lastname').val();
			jQuery('#shipping_lastname').val(bill_lname);
		}

	});

	jQuery('#billing_country_id').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_country = jQuery('#billing_country_id').val();
			jQuery('#shipping_country_id').val(bill_country);
		}

	});

	jQuery('#billing_postcode').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_postcode = jQuery('#billing_postcode').val();
			jQuery('#shipping_postcode').val(bill_postcode);
		}

	});


	jQuery('#billing_region_id').change(function() {
		var billing_region = jQuery('#billing_region_id').val();

		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			jQuery('#shipping_region_id').val(billing_region);

			setTimeout(function(){
				jQuery('input[name=shippingmethod').prop('checked', true).trigger('click');
				
			}, 2000);
		}
	});

	jQuery('#billing_city').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_city = jQuery('#billing_city').val();
			jQuery('#shipping_city').val(bill_city);
		}

	});


	jQuery('#billing_street1').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_street = jQuery('#billing_street1').val();
			jQuery('#shipping_street1').val(bill_street);
		}

	});

	jQuery('#billing_telephone').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_tel = jQuery('#billing_telephone').val();
			jQuery('#shipping_telephone').val(bill_tel);
		}

	});

	jQuery('#billing_mobile').change(function() {
		if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
			var bill_mobile = jQuery('#billing_mobile').val();
			jQuery('#shipping_mobile').val(bill_mobile);
		}
	});


	//if customer has no address
	jQuery(document).ready(function (){	
		

		var addressid = jQuery('#billing_address_id').val();
			if(addressid == 0){
				// alert(addressid);
					jQuery('#billing_address_form').change(function () {

						var newbillingdata = jQuery("#billing_address_form").serialize();
								jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveanotherBilling/', 
								newbillingdata,

								function (newbillingdata)
								{
									var dataobj = jQuery.parseJSON(newbillingdata);

										if (dataobj.reload == true)
										{
														
												//billing address is saved
												jQuery('#shipping_address_form').change(function () {
												var newshippingdata = jQuery("#shipping_address_form").serialize();
														jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveanotherShipping/', 
														newshippingdata,

														function (newshippingdata)
														{
															var dataobj = jQuery.parseJSON(newshippingdata);

																if (dataobj.reload == true)
																{
																				
																		// jQuery("#shippingmethod").click();
																		// alert(dataobj.reload);
																		// location.reload();
																		//billing address is saved
																					
																}else{

																	return;

																}
															

														}
													);
												});
															
										}else{

											return;

										}
									

								}
							);
					});
				
			}

	});

	jQuery(document).on('change','#billing_region_id', function(){
		
		var data = jQuery(this).val(); 

		jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: data }, function(res){				
			jQuery("#billing_city").html(res);
		});


		if(document.getElementById('billing_use_for_shipping_yes').checked){
			jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: data }, function(res){				
				jQuery("#shipping_city").html(res);
			});
		}
	});
	
	//END BILLING ADDRESS
	
	//END SHIPPING ADDRESS
	jQuery('#shipping_save_in_address_book_yes').click(function(){

		if(confirm('Do you want to save your shipping address?')){
			jQuery("#shipping_save_in_address_book").click();
			jQuery("#shipping_save_in_address_book").val(1);
		}

	});

	//DYNAMIC VARIABLES - leandro
	var currentPage = 'page-1-shipping';
	var showBillingAddress = 'no';
	var showPlaceOrderAlready = 'no';
	var pageDone = {
		'pageOne' : true,
		'pageTwo' : false,
		'pageThree' : false
	};
	//END of DYNAMIC VARIABLES - leandro
	jQuery(document).ready(function (){	
		jQuery.noConflict();
		//Initiate the Show&Hide page - leandro
		showPageOne();
		check(jQuery('#shipping_region_id').val(),jQuery('#shipping_city').val());
		jQuery(document).on('change','#shipping_city', function(){
			check(jQuery('#shipping_region_id').val(),jQuery('#shipping_city').val());
		});

		jQuery(document).on('change','#shipping_region_id', function(){
			check(jQuery('#shipping_region_id').val(),jQuery('#shipping_city').val());

		});
	
		function check(state_id,city_id)
		{		

			var array_state ='<?php $stateprovince2 = Mage::getStoreConfig('payment/cashondelivery/stateprovince');
								$default_state = '';
								$stateprovince2 = explode(',', $stateprovince2);

								foreach($stateprovince2 as $stateprovince){
									$default_state .= $stateprovince .","; 
								} 
								echo substr($default_state,0,-1); ?>';



			var array_city ='<?php $city2 = Mage::getStoreConfig('payment/cashondelivery/city');
								$default_city = ''; 
								$city2 = explode(',', $city2);
								foreach($city2 as $city){ 
										$default_city .= $city .","; } 
								echo substr($default_city,0,-1); ?>';

		
			var splitObj = array_state.split(","); 
			var splitObj2 = array_city.split(",");
			

			if(jQuery.inArray(state_id, splitObj) !=-1 && jQuery.inArray(city_id, splitObj2) !=-1){
				jQuery('#cashondelivery').attr('disabled', false);
				jQuery("label[for='p_method_cashondelivery']").attr('disabled', false);

			}else{
				jQuery('#cashondelivery').attr('disabled', true);
				jQuery('#cashondelivery').removeAttr("checked");
				jQuery("#cashondelivery_name").css('display', 'none');

			}
		}


		function selectAddress_shipping(addressid)
		{
			var addID = addressid; //jQuery(this).val();		

			jQuery.post( '<?php echo Mage::getBaseUrl();?>rracheckout/address/addressbill',{ 
				addressID: addID
				},
				function (addressData)
				{
				var dataobj = jQuery.parseJSON(addressData); 

				if (dataobj.success == true)
				{

					jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: dataobj.region_id, city_id: dataobj.city }, function(res){				
						jQuery("#shipping_city").html(res);
						check(jQuery('#shipping_region_id').val(),jQuery('#shipping_city').val());
					});
					
					jQuery('#shippingAddressId').val(addressid);
					jQuery('#shipping_firstname').val(dataobj.firstname);
					jQuery('#shipping_lastname').val(dataobj.lastname);
					
					jQuery('#shipping_country_id').val(dataobj.country_id);
					jQuery('#shipping_postcode').val(dataobj.postcode);				
					
					jQuery('#shipping_telephone').val(dataobj.telephone);
					jQuery('#shipping_mobile').val(dataobj.mobile);
					jQuery('#shipping_street1').val(dataobj.street);
					
					jQuery('#shipping_region_id').val(dataobj.region_id);
					jQuery('#shipping_region').val(dataobj.region);
					jQuery('#shipping_city').val(dataobj.city);
					
					jQuery('span.shipping_desc').css('display', 'none');
					jQuery('input[name=shippingmethod]').attr('checked', false);

					var paymentdata = jQuery('#shipping_address_form').serialize();
				
						jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/savenewShipping/', 
						
						paymentdata,

						function (paymentdataretship)
						{

							var dataobj = jQuery.parseJSON(paymentdataretship);

							if (dataobj.reload == true)
							{
								jQuery("#shippingmethod").click();	
								//location.reload(true);
							}else{

								return;
							}

						});	
				}else{

					jQuery('#shipping_firstname').val('');
					jQuery('#shipping_lastname').val('');
					
					// jQuery('#shipping_country_id').val('');
					jQuery('#shipping_postcode').val('');				
					
					jQuery('#shipping_city').val('');
					jQuery('#shipping_telephone').val('');
					jQuery('#shipping_mobile').val('');
					jQuery('#shipping_street1').val('');
					
					jQuery('#shipping_region_id').val('');
					jQuery('#shipping_region').val('');
					jQuery('#shipping_siab').show();

				}
			});
		}

		jQuery('.shipping_address_id').click(function () {
			var addressid = jQuery(this).val();
			selectAddress_shipping(addressid);
		});

		// function onchangeShippingSave()
		// {
			jQuery('#shipping_address_form').change(function () {
				var paymentdata = jQuery('#shipping_address_form').serialize();
				
				jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/savenewShipping/', 
				
				paymentdata,

				function (paymentdataretship)
				{

					var dataobj = jQuery.parseJSON(paymentdataretship);

					if (dataobj.reload == true)
					{
						jQuery("#shippingmethod").click();	
						//location.reload(true);
					}else{

						return;
					}

				});	
			});	
		//}


		jQuery('#shipping_save_in_address_book').change(function () {

			if(jQuery('#shipping_save_in_address_book').is(':checked')){
			jQuery("#shipping_save_in_address_book").val(1);

				var shippingaddressdata = jQuery('#shipping_address_form').serialize();
				jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveanotherShipping/', 
					shippingaddressdata,

					function (shipdataretship)
					{
						var dataobj = jQuery.parseJSON(shipdataretship);

						if (dataobj.reload == true)
						{
							jQuery("#shippingmethod").click();	
						}else{
							return;
						}
					}
				);

			}else{
				jQuery("#shipping_save_in_address_book").val(0);
			}

			jQuery("#shipping_save_in_address_book").val(1);

		});
		 
		jQuery(document).on('change','#shipping_region_id', function(){

			var data = jQuery(this).val(); 

			jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: data }, function(res){				
			jQuery("#shipping_city").html(res);
			});

			jQuery('span.shipping_desc').css('display', 'none');
			jQuery('input[name=shippingmethod').attr("checked", false);

		});


		// shared function - leandro
		function updateFromShippingSummary(){
			jQuery('#shipping_fname').html(jQuery('#shipping_firstname').val() + '&nbsp;');
			jQuery('#shipping_lname').html(jQuery('#shipping_lastname').val());
			jQuery('#shipping_addres').html(jQuery('#shipping_street1').val());
			jQuery('#shipping_city_2').html(jQuery('#shipping_city option:selected').text());
			jQuery('#shipping_region_2').html(jQuery('#shipping_region_id option:selected').text());
			jQuery('#shipping_country').html(jQuery('#shipping_country_id').val());
			jQuery('#shipping_postcode2').html(jQuery('#shipping_postcode').val());
			jQuery('#shipping_mobile_num').html(jQuery('#shipping_mobile').val());


			if(showBillingAddress == 'no'){
				jQuery('#billingAddressId').val(jQuery('#shippingAddressId').val());
				jQuery('#billing_firstname').val(jQuery('#shipping_firstname').val());
				jQuery('#billing_lastname').val(jQuery('#shipping_lastname').val());
				jQuery('#billing_country_id').val(jQuery('#shipping_country_id').val());
				jQuery('#billing_postcode').val(jQuery('#shipping_postcode').val());
				jQuery('#billing_telephone').val(jQuery('#shipping_mobile').val());
				jQuery('#billing_mobile').val(jQuery('#shipping_mobile').val());
				jQuery('#billing_street1').val(jQuery('#shipping_street1').val());
				jQuery('#billing_region_id').val(jQuery('#shipping_region_id option:selected').val());
				jQuery('#billing_region').val(jQuery('#shipping_region_id option:selected').html());

				jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/webuiltthiscity', {
					region_id: jQuery('#shipping_region_id option:selected').val(), 
					cityval: jQuery('#shipping_city option:selected').text()
				}, function(res){				
					jQuery("#billing_city").html(res);
					jQuery('#billing_city option:selected').html(jQuery('#shipping_city option:selected').html());
					jQuery('#billing_city').val(jQuery('#shipping_city option:selected').val());
				});
			}
			jQuery('#billing_fname').html(jQuery('#shipping_firstname').val());
			jQuery('#billing_lname').html(jQuery('#shipping_lastname').val());
			jQuery('#billing_address').html(jQuery('#shipping_street1').val());
			jQuery('#billing_city_2').html(jQuery('#shipping_city option:selected').text());
			jQuery('#billing_region_2').html(jQuery('#shipping_region_id option:selected').text());
			jQuery('#billing_country').html(jQuery('#shipping_country_id').val());
			jQuery('#billing_postcode2').html(jQuery('#shipping_postcode').val());
			jQuery('#billing_mobile_2').html(jQuery('#shipping_mobile').val());

		};

		function updateFromBillingSummary(){
			jQuery('#billing_fname').html(jQuery('#billing_firstname').val() + '&nbsp;');
			jQuery('#billing_lname').html(jQuery('#billing_lastname').val());
			jQuery('#billing_address').html(jQuery('#billing_street1').val());
			jQuery('#billing_city_2').html(jQuery('#billing_city option:selected').text());
			jQuery('#billing_region_2').html(jQuery('#billing_region_id option:selected').text());
			jQuery('#billing_country').html(jQuery('#billing_country_id').val());
			jQuery('#billing_postcode2').html(jQuery('#billing_postcode').val());
			jQuery('#billing_mobile_2').html(jQuery('#billing_mobile').val());
		};
		function showPageOne(){
			jQuery('.shipping-address').fadeIn('slow');
			jQuery('.shipping-method').hide();
			jQuery('.payment-method').hide();
			jQuery('.billing-address').hide();
			jQuery('.orderview-wrapper').hide();
			pageDone['pageOne'] = true;
			currentPage = 'page-1-shipping';
			 jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._shipping .shipping_').css('display', 'inline-block');
		    jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._payment .payment_').css('display', 'none');
		    jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment').css('border-top', '5px solid #fff');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment_link').css('color', '#fff');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeholder').css('border-top', '5px solid #fff');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeorder_link').css('color', '#fff');
		    jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._placeholder .placeholder_').css('display', 'none');

		}
		function showPagetwo(){
			var isChecked = jQuery('#yes-billing:checked').val()?1:0;
			var notChecked = jQuery('#no_billing:checked').val()?1:0;
		  	var check_billing = isChecked + notChecked;
		  
		  	jQuery('.checkout-nav').show();
		 	if(!jQuery('#shipping_firstname').val() || !jQuery('#shipping_lastname').val() || !jQuery('#shipping_mobile').val() || !jQuery('#shipping_postcode').val() || check_billing == 0 || !jQuery('#shipping_city').val() || !jQuery('#shipping_street1').val() || !jQuery('#shipping_region_id').val() || !jQuery('#shipping_country_id').val() ){
		  	
		  		alert('Please fill up all the required fields');

		  		return false;
		  	}

		  	jQuery('.shipping-address').hide();
			jQuery('.shipping-method').fadeIn('slow');
			jQuery('.payment-method').hide();
			jQuery('.billing-address').hide();
			jQuery('.orderview-wrapper').hide();

			currentPage = 'page-2-shipping-option';
			pageDone['pageTwo'] = true;
		
		  	return true;
		}
		function showPagethree(){
			var isSelected = jQuery('.shipping_method:checked').val()?1:0;

			jQuery('.checkout-nav').show();
			if(isSelected == 0){
				alert('Please select your shipping option');
				return false;
			}
			jQuery('.shipping-address').hide();
			jQuery('.shipping-method').hide();
			jQuery('.payment-method').fadeIn('slow');
			jQuery('.billing-address').hide();
			jQuery('.orderview-wrapper').hide();
			currentPage = 'page-3-payment-option';
			pageDone['pageThree'] = true;

			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._shipping .shipping_').css('display', 'none');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._payment .payment_').css('display', 'inline-block');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment').css('border-top', '5px solid #ffff00');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment_link').css('color', '#ffff00');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._placeholder .placeholder_').css('display', 'none');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeholder').css('border-top', '5px solid #fff');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeorder_link').css('color', '#fff');

			if(jQuery('[name="payment[method]"]:checked').val() == 'bankdeposit'){
				jQuery('#payment_instruction_bankdeposit').show();
			}
		  	return true;
		}

		function showPageFour(){
			var isSelected = jQuery('.payment_method:checked').val()?1:0;

			jQuery('.checkout-nav').show();
			if(isSelected == 0){
				alert('Please select a payment method');
				return false;
			}

			var getPayment = jQuery("input[name='payment[method]']:checked").val();
			var getPaymentName = '';

			if(getPayment == 'perapal'){
				getPaymentName = 'Cebuana Lhuillier';
			}else if(getPayment == 'bpisecurepay'){
				getPaymentName = 'Bank Deposit';
			}else if(getPayment == 'cashondelivery'){
				getPaymentName = 'Cash On Delivery';
			}else if(getPayment == 'bankdeposit'){
				getPaymentName = 'Bank Deposit';
			}
			jQuery('#payment_method').html(getPaymentName);



			jQuery('.shipping-address').hide();
			jQuery('.shipping-method').hide();
			jQuery('.payment-method').hide();

			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._shipping .shipping_').css('display', 'none');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment').css('border-top', '5px solid #ffff00');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment_link').css('color', '#ffff00');

			//this shows weather billing or placing order page will be shown - leandro
			if(showBillingAddress == 'yes'){
				jQuery('.billing-address').fadeIn('slow');
				currentPage = 'page-4-billing-add';
				jQuery('.orderview-wrapper').hide();
				updateFromBillingSummary();
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._payment .payment_').css('display', 'inline-block');
				
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._placeholder .placeholder_').css('display', 'none');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeholder').css('border-top', '5px solid #fff');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeorder_link').css('color', '#fff');
			}else{
				jQuery('.checkout-nav').hide();
				jQuery('.orderview-wrapper').fadeIn('slow');
				onchangeBillingSave();
				showPlaceOrderAlready = 'yes';
				updateFromShippingSummary();
				
				currentPage = 'page-5-review';
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._payment .payment_').css('display', 'none');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._placeholder .placeholder_').css('display', 'inline-block');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeholder').css('border-top', '5px solid #ffff00');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeorder_link').css('color', '#ffff00');
			}

			return true;
		}

		function showPageFive(){
			if(!jQuery('#billing_firstname').val() || !jQuery('#billing_lastname').val() || !jQuery('#billing_mobile').val() || !jQuery('#billing_street1').val() || !jQuery('#billing_city').val() || !jQuery('#billing_postcode').val() || !jQuery('#billing_region_id').val() || !jQuery('#billing_country_id').val()){
			  	 alert('Please fill up all the required fields');
			  	 return false;
			}

			jQuery('.shipping-address').hide();
			jQuery('.shipping-method').hide();
			jQuery('.payment-method').hide();
			jQuery('.billing-address').hide();
			jQuery('.orderview-wrapper').fadeIn('slow')
			onchangeBillingSave();
			showPlaceOrderAlready = 'yes';
			jQuery('.checkout-nav').hide();

			if(showBillingAddress == 'yes'){
				updateFromBillingSummary();			
			}else{
				updateFromShippingSummary();
			}
			currentPage = 'page-5-review';

			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._shipping .shipping_').css('display', 'none');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._payment .payment_').css('display', 'none');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment').css('border-top', '5px solid #ffff00');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment_link').css('color', '#ffff00');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._placeholder .placeholder_').css('display', 'inline-block');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeholder').css('border-top', '5px solid #ffff00');
			jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeorder_link').css('color', '#ffff00');

			return true;
		}


		// END shared function - leandro
		// DOM events - leandro

		jQuery(document).on('change', '.shipping-address input', function(){
			updateFromShippingSummary();
		});

		jQuery(document).on('change', '#payment-method-form', function(){
			var get_payment = jQuery("input[name='payment[method]']:checked").val();
			var get_payment_name = '';

			if(get_payment == 'perapal'){
				get_payment_name = 'Cebuana Lhuillier';
			}else if(get_payment == 'bpisecurepay'){
				get_payment_name = 'Bank Deposit';
			}else if(get_payment == 'cashondelivery'){
				get_payment_name = 'Cash On Delivery';
			}else if(get_payment == 'bankdeposit'){
				get_payment_name = 'Bank Deposit';
			}
			jQuery('#payment_method').html(get_payment_name);
		});

		jQuery(document).on('change', '.shipping-address select', function(){
			updateFromBillingSummary();
		});

		jQuery('[name="select-billing"]').change(function(){
			var selecteVal = jQuery(this).val();
 
			if(selecteVal != 0){
				showBillingAddress = 'no';
				updateFromShippingSummary();
			}else{
				showBillingAddress = 'yes';
				updateFromBillingSummary();
			}
		});


		function manualFormValidation(formId){
			jQuery.noConflict();
			var formEvent = new VarienForm(formId, true);
			var e = null;

            try {
                formEvent.validator.validate();
            } catch (e) {
            	console.log('form submitted might not exist - see the log below'); // - leandro
            	console.log(e);
            }

		};


		jQuery(document).on('click', '.checkout-paging', function(){
			var response = false;

			switch(currentPage){
				case 'page-1-shipping':
				    manualFormValidation('shipping_address_form');
					showPagetwo();
					break;
				case 'page-2-shipping-option':
					showPagethree();
					break;
				case 'page-3-payment-option':
				 	showPageFour();
					break;
				case 'page-4-billing-add':
					manualFormValidation('billing_address_form');
					showPageFive();
					break;
			}

		});
		
		jQuery(document).on('click', 'td .shipping_link, span#go-back-address' ,function(){
			showPageOne();
			jQuery('.checkout-nav').show();
		});
		jQuery(document).on('click', 'td .payment_link, span#go-back-payment-method' ,function(){
			jQuery('.checkout-nav').show();
			if(pageDone['pageOne'] && pageDone['pageTwo']){
				showPagethree();
			}else{
				alert('Please fill up all the required fields');
			}
			
		});
		jQuery(document).on('click', 'td .placeorder_link' ,function(){
			jQuery('.checkout-nav').show();
			if(!pageDone['pageOne'] || !pageDone['pageTwo'] || !pageDone['pageThree']){
				alert('Please fill up all the required fields');
				return false;
			}

			jQuery('.shipping-address').hide();
			jQuery('.shipping-method').hide();
			jQuery('.payment-method').hide();
			

			//this shows weather billing or placing order page will be shown - leandro
			if(showBillingAddress == 'yes'){
				jQuery('.orderview-wrapper').hide();
				jQuery('.billing-address').fadeIn('slow');
				currentPage = 'page-4-billing-add';
				updateFromBillingSummary();
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._shipping .shipping_').css('display', 'none');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment').css('border-top', '5px solid #ffff00');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment_link').css('color', '#ffff00');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._payment .payment_').css('display', 'inline-block');
					
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._placeholder .placeholder_').css('display', 'none');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeholder').css('border-top', '5px solid #fff');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeorder_link').css('color', '#fff');
			}else{
				var billingAddressOption = jQuery('[name="select-billing"]').val();
				updateFromShippingSummary();
				jQuery('.checkout-nav').hide();
				jQuery('.orderview-wrapper').fadeIn('slow');
				onchangeBillingSave();
				currentPage = 'page-5-review';

				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._shipping .shipping_').css('display', 'none');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._payment .payment_').css('display', 'none');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment').css('border-top', '5px solid #ffff00');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .payment_link').css('color', '#ffff00');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline_t ._placeholder .placeholder_').css('display', 'inline-block');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeholder').css('border-top', '5px solid #ffff00');
				jQuery('.rracheckout-checkout-onepage .right-menu .cart_timeline .placeorder_link').css('color', '#ffff00');
			}
		});
		
		jQuery(document).on('click', 'span#go-back-address2', function(){
			document.getElementById('no_billing').checked = true;
			showBillingAddress = 'yes';
			showPageFour();
		});
		// End DOM events - leandro
		

	}); // END of document ready
//TRY TO PLACE YOUR EVENT INSIDE OF .READY above, thanks - leandro
</script>


