<?php
	//$healthplusData = Mage::getModel('healthplus/healthplus')->healthplusData();

		$connection = Mage::getSingleton('core/resource')->getConnection('core_write');

		$_order = $this->getOrder();
		$orderid = $_order->getIncrementId();

		$order = Mage::getModel('sales/order')->loadByIncrementId($orderid);
		$customer_email = $order->getCustomerEmail(); 
				
		$sql = "SELECT * FROM unilab_health_plus WHERE email ='$customer_email'";
		$row = $connection->fetchRow($sql);
        $connection->commit();
		
		$response['credit_earned'] = $row['credit_earned'];
		$response['credit_use'] = $row['credit_use'];
		$response['credit_balance'] = $row['credit_balance'];
		$response['available_balance'] = $row['available_balance'];

?>
  
<table cellspacing="0" cellpadding="0" border="0" width="650" style="margin: 0 auto";>
	<tr>
		<th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Health Plus Credits:</th>
	</tr>
	
	<tr>
		<td valign="top" style="font-size:12px; padding:7px 9px 9px 9px; border-left:1px solid #EAEAEA; border-bottom:1px solid #EAEAEA; border-right:1px solid #EAEAEA;">

			<table>
				<tr>
					<td>
						<strong>Total Credits earned:</strong> <?php echo Mage::helper('core')->currency($row['credit_earned'],true,false); ?>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Total Credits used:</strong> <?php echo Mage::helper('core')->currency($row['credit_use'],true,false); ?>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Credit Balance:</strong> <?php echo Mage::helper('core')->currency($row['credit_balance'],true,false); ?>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Available Credit Balance:</strong>  <?php echo Mage::helper('core')->currency($row['available_balance'],true,false);?>
					</td>
				</tr>
			</table>

		</td>
	</tr>
	
</table>

