<?php $count = (int) $this->helper('checkout/cart')->getSummaryCount(); ?>

<div class="sub-topmenu">
	<ul>
		 <?php 
		if(!Mage::getSingleton('customer/session')->isLoggedIn()){
		?>  
			<li><a href="<?php echo Mage::getUrl('customer/account/login'); ?>"><?php echo $this->__("Login");?></a></li>
			<li><a href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__("Signup");?></a></li> 

		<?php } else {?>
		
			<li><a href="<?php echo Mage::getUrl('customer/account'); ?>"><?php echo $this->__("My Account");?></a></li>
			<li><a href="<?php echo Mage::getUrl('customer/account/logout'); ?>"><?php echo $this->__("Logout");?></a></li>
			
		<?php } ?>
		
			<li><a href="<?php echo Mage::helper('checkout/cart')->getCartUrl() ?>">View Cart <?php echo "($count)"; ?></a></li>
			<li><a  href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl() ?>"><?php echo $this->__('Checkout')?></a></li>
	</ul>    
</div>	

<div class="sub-topmenu nav2">	
	<ul>
		 <?php 
		if(!Mage::getSingleton('customer/session')->isLoggedIn()){
		?>  
			<li><a href="<?php echo Mage::getUrl('customer/account/login'); ?>"><?php echo $this->__("Login");?></a></li>
			<li><a href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__("Signup");?></a></li> 

		<?php } else {?>
		
			<li><a href="<?php echo Mage::getUrl('customer/account'); ?>"><?php echo $this->__("My Account");?></a></li>
			<li><a href="<?php echo Mage::getUrl('customer/account/logout'); ?>"><?php echo $this->__("Logout");?></a></li>
			
		<?php } ?>
		
	</ul>
	
	<ul>
			<li><a href="<?php echo Mage::helper('checkout/cart')->getCartUrl() ?>">View Cart <?php echo "($count)"; ?></a></li>
			<li><a  href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl() ?>"><?php echo $this->__('Checkout')?></a></li>
	</ul> 
	
</div>