 <style>
html[data-useragent*='MSIE 10.0'] body {
  line-height: 1 !important;
}
 </style>

<html data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
 <div class="account-create">

    <div class="page-title">

        <h1><?php echo $this->__('Register New Account') ?></h1>

    </div>

    <?php echo $this->getChildHtml('form_fields_before')?>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">

        <div class="fieldset">

            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>

            <hr class="div">

            <ul class="form-list">

                <li class="fields">

                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

                    <div class="input-box">

                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />

                    </div>

                </li>

                <li class="fields">

                    <!-- <div class="field"> -->

                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                        <div class="input-box">

                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />

                        </div>

                    <!-- </div> -->

                    <!-- <div class="field"> -->

                </li>

                <li class="fields">

                

                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>

                        <div class="input-box">

                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />

                        </div>

                    <!-- </div> -->

                </li> 

                <?php // echo $this->getChildHtml('persistent.remember.me'); ?>

            </ul> 

        </div>

        <div class="fieldset">

            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />

            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>

            <hr class="div">

            <ul class="form-list">

                <li class="fields">

                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                </li>



            <?php $_civil_status = $this->getLayout()->createBlock('customer/widget_civilstatus') ?>

            <?php if ($_civil_status->isEnabled()): ?>

                <li class="ddl-reg fields"><?php echo $_civil_status->setCivilStatus($this->getFormData()->getCivilStatus())->toHtml() ?></li>

            <?php endif ?>



            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>

            <?php if ($_taxvat->isEnabled()): ?>

                <li class="ddl-reg fields"><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>

            <?php endif ?>



            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

            <?php if ($_gender->isEnabled()): ?>

                <li class="ddl-reg-gender fields"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>

            <?php endif ?>



            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>

            <?php if ($_dob->isEnabled()): ?>

                <li class="fields"><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>

            <?php endif ?>

            </ul>

        </div>

    <?php // if($this->getShowAddressFields(true)): ?>

        <div class="fieldset">

            <input type="hidden" name="create_address" value="1" />

            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>

            <hr class="div">

            <ul class="form-list">

                <li class="fields">

                    <!-- <div class="field"> -->

                        <label style="margin: 5px 25px; width: 120px !important;" for="company"><?php echo $this->__('Company') ?></label>

                        <div class="input-box">

                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />

                        </div>

                    <!-- </div>                     -->

                </li>

                <li class="fields"> 

                     <!-- <div class="field"> -->

                        <label for="mobile" class="required"><em>*</em><?php echo $this->__('Mobile') ?></label>

                        <div class="input-box">

                            <input type="text" name="mobile" id="mobile" value="<?php echo $this->escapeHtml($this->getFormData()->getMobile()); ?>" title="<?php echo $this->__('Mobile') ?>" maxlength="13"  class="validate-contactnumber-require-one input-text <?php //echo $this->helper('customer/address')->getAttributeValidationClass('mobile') ?>" />

                        </div>

                    <!-- </div> -->

                </li>

               <li class="fields">

                    <!-- <div class="field"> -->

                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

                        <div class="input-box">

                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" maxlength="11"  class="validate-contactnumber-require-one input-text <?php //echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />

                        </div>

                    <!-- </div> -->

                    

                </li>

                <li class="ddl-reg fields">

                    <!-- <div class="field"> -->

                        <label for="country" style="margin: 5px 10px;" class="ddl-reg required"><em>*</em><?php echo $this->__('Country') ?></label>

                        <div class="input-box">

                            <?php echo $this->getCountryHtmlSelect() ?>

                        </div>

                    <!-- </div> -->

                </li>

                <li class="ddl-reg fields">

                    <!-- <div class="field"> -->

                        <label for="region_id" style="margin: 5px 10px;" class="ddl-reg required"><em>*</em><?php echo $this->__('State/Province') ?></label>

                        <div class="input-box">

                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">

                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>

                            </select>

                            <script type="text/javascript">

                            //<![CDATA[

                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");

                            //]]>

                            </script>

                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />

                        </div>

                    <!-- </div> -->

                </li>

                  <li class="ddl-reg fields">

                    <!-- <div class="field"> -->

                        <label for="city" style="margin: 5px 10px;" class="ddl-reg required"><em>*</em><?php echo $this->__('Town/City') ?></label>

                        <div class="input-box">

                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />

                        </div>

                    <!-- </div> -->

                </li>

                <li class="fields">

                    <!-- <div class="field"> -->

                        <!-- <label style="margin: 5px 25px; width: 120px !important;" for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label> -->

                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>

                        <div class="input-box">

                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />

                        </div>

                    <!-- </div> -->

                </li>

            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>

                <li class="fields">

                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>

                    <div class="input-box">

                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />

                    </div>

                </li>

            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

            <div style="display:none;">

            <?php for ($_i = 1, $_n = $this->helper('customer/address')->getStreetLines()-1; $_i <= $_n; $_i++): ?>

                <li class="wide">

                    <div class="input-box">

                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />

                    </div>

                </li>

            <?php endfor; ?>

            </div>

                

                <!--

                <li>

                    <div class="field">

                        <label for="city_dropdown" class="required"><em>*</em><?php echo $this->__('City Testing') ?></label>

                        <div class="input-box">

                            <select id="city_dropdown" class="validate-select">

                                <option value="">-Please Select One-</option>                               

                            </select>

                        </div>

                    </div>

                </li>

                -->

                

              

            </ul>

            <input type="hidden" name="default_billing" value="1" />

            <input type="hidden" name="default_shipping" value="1" />

        </div>

    <?php //endif; ?> 

        <div class="fieldset">

            <h2 class="legend"><?php echo $this->__('Security Check') ?></h2>

            <hr class="div">

            <ul class="form-list captcha">



                <?php echo $this->getChildHtml('form.additional.info'); ?>

                <?php //echo $this->getChildHtml('persistent.remember.me'); ?>

            </ul>

            <?php //echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

        </div>

        

        <div class="fieldset">

            <hr class="div">

            <ul class="form-list">

                <?php if ($this->isNewsletterEnabled()): ?>

                <li class="control">

                        <div class="input-box div_checkbox">

                            <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('I want to receive email from WPSI and its partners') ?>" value="1" id="is_subscribed" class="checkbox" />

                            <label class="terms" for="is_subscribed"><?php echo $this->__('I want to receive email from WPSI and its partners') ?></label>

                        </div>

                </li>

                <?php endif ?>

                 <?php $_terms = $this->getLayout()->createBlock('customer/widget_terms') ?>

                <?php if ($_terms->isEnabled()): ?>

                    <li class="control"><?php echo $_terms->setAgreeOnTerms($this->getFormData()->getAgreeOnTerms())->toHtml() ?></li>

                <?php endif ?> 

            </ul>

            <div class="clear"></div>

        </div>

        <div class="buttons-set">

            <p class="required"><?php echo $this->__('* Required Fields') ?></p>

            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>

            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>

        </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>

            <input name="context" type="hidden" value="checkout" />

        <?php endif; ?>

    </form>

    <script type="text/javascript">

    //<![CDATA[

        var dataForm = new VarienForm('form-validate', true);

        

        RegionUpdater.prototype.update = RegionUpdater.prototype.update.wrap(function(parentMethod){            

            parentMethod();         

            if(this.countryEl.value == "PH"){               

                if($("mobile") && $("mobile").value == "" ){

                    $("mobile").value = "+63";

                }

            }else{

                if($("mobile") && $("mobile").value != "" ){

                    $("mobile").value = "";

                }

            }           

        });       

        

      

        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');

        <?php /*  

        var requiredOne = (function(o) { 

            if(this.id == "telephone")

            {

                if(this.value == "" && ($('mobile').value == "+63" || $('mobile').value == "")){

                    this.up('.field').select('[for="'+this.id+'"]')[0].select('em')[0].update('*');

                    if($(this.id).hasClassName('required-entry')==false){

                        $(this.id).addClassName('required-entry');

                    }

                    

                    // Update mobile class setting

                    if($('mobile').hasClassName('validation-failed')){

                        $('mobile').removeClassName('validation-failed');

                    }

                    if($('mobile').hasClassName('required-ph-mobile') == false){

                        $('mobile').addClassName('required-ph-mobile');

                    }

                    if($('advice-required-ph-mobile-mobile')){

                        $('advice-required-ph-mobile-mobile').remove();

                    }

                    $('mobile').up('.field').select('[for="mobile"]')[0].select('em')[0].update('*');

                }

                else

                if(this.value != ""){

                    this.up('.field').select('[for="'+this.id+'"]')[0].select('em')[0].update('');

                    if($(this.id).hasClassName('required-entry')){

                        $(this.id).removeClassName('required-entry');

                    }

                    if($(this.id).hasClassName('validation-failed')){

                        $(this.id).removeClassName('validation-failed');

                    }

                    if($('advice-required-entry-'+this.id)){

                        $('advice-required-entry-'+this.id).remove();

                    }

                    

                    // Update mobile class setting

                    if($('mobile').hasClassName('validation-failed')){

                        $('mobile').removeClassName('validation-failed');

                    }

                    if($('mobile').hasClassName('required-ph-mobile')){

                        $('mobile').removeClassName('required-ph-mobile');

                    }

                    if($('advice-required-ph-mobile-mobile')){

                        $('advice-required-ph-mobile-mobile').remove();

                    }

                    $('mobile').up('.field').select('[for="mobile"]')[0].select('em')[0].update('');

                }

            }

            

            if(this.id == "mobile")

            {

                if( (this.value == "" || this.value == "+63") && $('telephone').value == ""){

                    this.up('.field').select('[for="'+this.id+'"]')[0].select('em')[0].update('*');

                    if($(this.id).hasClassName('required-ph-mobile')==false){

                        $(this.id).addClassName('required-ph-mobile');

                    }

                    

                    if($(this.id).hasClassName('validation-passed')){

                        $(this.id).removeClassName('validation-passed');

                    }

                    

                    

                    // Update mobile class setting

                    if($('telephone').hasClassName('validation-failed')){

                        $('telephone').removeClassName('validation-failed');

                    }

                    if($('telephone').hasClassName('required-entry') == false){

                        $('telephone').addClassName('required-entry');

                    }

                    if($('advice-required-entry-telephone')){

                        $('advice-required-entry-telephone').remove();

                    }

                    $('telephone').up('.field').select('[for="telephone"]')[0].select('em')[0].update('*');

                }

                else

                if(this.value != "" || this.value != "+63"){

                    this.up('.field').select('[for="'+this.id+'"]')[0].select('em')[0].update('');

                    if($(this.id).hasClassName('required-ph-mobile')){

                        $(this.id).removeClassName('required-ph-mobile');

                    }

                    if($(this.id).hasClassName('validation-failed')){

                        $(this.id).removeClassName('validation-failed');

                    }

                    if($('advice-required-entry-'+this.id)){

                        $('advice-required-entry-'+this.id).remove();

                    }

                    

                    // Update mobile class setting

                    if($('telephone').hasClassName('validation-failed')){

                        $('telephone').removeClassName('validation-failed');

                    }

                    if($('telephone').hasClassName('required-entry')){

                        $('telephone').removeClassName('required-entry');

                    }

                    if($('advice-required-entry-telephone')){

                        $('advice-required-entry-telephone').remove();

                    }

                    $('telephone').up('.field').select('[for="telephone"]')[0].select('em')[0].update('');

                }

            }

            

        });

        

        

        Event.observe('telephone', 'blur', requiredOne);

        Event.observe('mobile', 'blur', requiredOne);                

       

        

        document.observe("dom:loaded", function() {

            

            var country = $('country').value;

            var mobile = $('mobile').value;

            var telephone = $('telephone').value;       

                        

            if( 

                        

                ( mobile != '+63' && mobile != '' && country == "PH" && telephone == '') ||

                ( mobile != '' && country != "PH" && telephone == '') || 

                ( telephone != '' && mobile != '+63') || 

                ( (mobile == '+63' || mobile == '') && country && telephone != '')

                

            )

            {

                if($('mobile').hasClassName('required-ph-mobile')){

                    $('mobile').removeClassName('required-ph-mobile');                  

                }

                

                if($('telephone').hasClassName('required-entry')){

                    $('telephone').removeClassName('required-entry');

                    

                }

                $('mobile').up('.field').select('[for="mobile"]')[0].select('em')[0].update('');

                $('telephone').up('.field').select('[for="telephone"]')[0].select('em')[0].update('');              

            } 

            

        }); */?>

        

        var updater = new jQuery.CityUpdater('country','region_id','city','<?php echo json_encode(Mage::helper('citydropdown')->getCities()); ?>','<?php echo $this->getFormData()->getCity() ; ?>','PH');        

        

        jQuery(document).ready(function($){

            $('#country').change(function(e){

                var streets = $('input[id=street_1]');

                if(streets.length > 0){

                    streets.each(function(i,elm){

                        $(elm).val(''); 

                    });

                } 

            }); 

            $('select#region_id').change(function(e){

                if($(this).val() == ""){

                    return ;

                }

                var streets = $('input[id=street_1]');

                if(streets.length > 0){

                    streets.each(function(i,elm){

                        $(elm).val(''); 

                    });

                } 

            });

            $("#mobile, #telephone").keydown(function (e) {
                // Allow: backspace, delete, tab, escape, enter and .
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                     // Allow: Ctrl+A, Command+A
                    (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) || 
                     // Allow: home, end, left, right, down, up
                    (e.keyCode >= 35 && e.keyCode <= 40)) {
                         // let it happen, don't do anything
                         return;
                }
                // Ensure that it is a number and stop the keypress
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });

        });

    //]]>

    </script>

</div>

<script>
var doc = document.documentElement;
doc.setAttribute('data-useragent', navigator.userAgent);
</script>