<?php
$installer = $this;
$installer->startSetup();
$installer->run("
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Bangued');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Boliney');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Bucay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Bucloc');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Daguioman');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Danglas');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Dolores');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','La Paz');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Lacub');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Lagangilang');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Lagayan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Langiden');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Licuan-Baay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Luba');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Malibcong');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Manabo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Peñarrubia');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Pidigan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Pilar');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Sallapadan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','San Isidro');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','San Juan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','San Quintin');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Tayum');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Tineg');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Tubo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','485','AB','Villaviciosa');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','486','AN','Butuan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','486','AN','Cabadbaran');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','487','AS','Bayugan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','489','AL','Legazpi');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','489','AL','Ligao');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','489','AL','Tabaco');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','493','BL','Isabela');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','493','BL','Lamitan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','494','BA','Balanga');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','496','BT','Batangas');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','496','BT','Lipa');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','496','BT','Tanauan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','496','BT','Baguio');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','499','BH','Tagbilaran');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','500','BK','Malaybalay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','500','BK','Valencia');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','501','BU','Malolos');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','501','BU','Meycauayan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','501','BU','San Jose del Monte');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','502','CG','Tuguegarao');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','504','CS','Iriga');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','504','CS','Naga ');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','506','CP','Roxas');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','508','CA','Bacoor');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','508','CA','Cavite');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','508','CA','Dasmariñas');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','508','CA','Imus');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','508','CA','Tagaytay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','508','CA','Trece Martires');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Bogo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Cebu');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Carcar');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Danao');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Lapu-Lapu');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Mandaue');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Naga');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Talisay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','509','CB','Toledo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','511','CO','Kidapawan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','512','DN','Panabo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','512','DN','Samal');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','512','DN','Tagum');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','513','DS','Davao');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','513','DS','Digos');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','514','DR','Mati');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','516','ES','Borongan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','519','IN','Batac');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','519','IN','Laoag');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','520','IS','Candon');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','520','IS','Vigan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','521','IL','Iloilo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','521','IL','Passi');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','522','IB','Cauayan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','522','IB','Ilagan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','522','IB','Santiago');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','523','KA','Tabuk');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','524','LU','San Fernando');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','525','LA','Biñan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','525','LA','Cabuyao');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','525','LA','Calamba');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','525','LA','San Pablo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','525','LA','San Pedro');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','525','LA','Santa Rosa');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','526','LN','Iligan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','527','LS','Marawi');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','528','LE','Baybay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','528','LE','Ormoc ');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','528','LE','Tacloban ');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','529','MG','Cotabato');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','531','MA','Masbate');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Caloocan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Las Piñas');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Makati');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Malabon');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Mandaluyong');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Marikina');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Muntinlupa');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Navotas');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Parañaque');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Pasay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Pasig');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Quezon');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','San Juan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Taguig');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','532','MM','Valenzuela');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','533','MO','Oroquieta');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','533','MO','Ozamiz');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','533','MO','Tangub');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','534','MR','Cagayan de Oro');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','534','MR','El Salvador');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','534','MR','Gingoog');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Bacolod');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Bago');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Cadiz');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Escalante');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Himamaylan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Kabankalan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','La Carlota');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Sagay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','San Carlos');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Silay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Sipalay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Talisay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','536','NO','Victorias');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','537','NR','Bais');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','537','NR','Bayawan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','537','NR','Canlaon');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','537','NR','Guihulngan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','537','NR','Dumaguete');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','537','NR','Tanjay');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','539','NE','Cabanatuan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','539','NE','Gapan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','539','NE','Palayan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','539','NE','San Jose');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','539','NE','Science  of Muñoz');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','541','OM','Abra de Ilog');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','542','RM','Calapan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','543','PL','Puerto Princesa');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','544','PA','Angeles ');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','544','PA','San Fernando');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','544','PA','Mabalacat');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','545','PG','Alaminos');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','545','PG','Dagupan ');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','545','PG','San Carlos');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','545','PG','Urdaneta');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','546','QZ','Lucena');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','546','QZ','Tayabas');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','548','RZ','Antipolo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','550','ES','Calbayog');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','550','ES','Catbalogan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','553','SO','Sorsogon');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','554','SC','General Santos ');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','554','SC','Koronadal');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','555','SL','Maasin');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','556','SK','Tacurong');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','558','SN','Surigao');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','559','SS','Bislig');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','560','SS','Tandag');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','560','TA','Tarlac');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','562','ZA','Olongapo');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','563','ZN','Dapitan');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','563','ZN','Dipolog');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','564','ZS','Pagadian');
insert into {$this->getTable('citydropdown/citydropdown')}(country_id,region_id,region_code,name) values('PH','564','ZS','Zamboanga');
		");

$installer->endSetup();