<?php $item = $this->getItem() ?>
<?php $items = $this->getChilds($item); ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>
<?php $_prevOptionId = '' ?>
<?php
    $orderId = Mage::app()->getRequest()->getParam('order_id');
    $minQty = 0;
?>

<?php if($this->getOrderOptions() || $item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php 
        $productId =  Mage::getModel("catalog/product")->getIdBySku($_item->getSku()); 
        if(!$productId){
            $productId = $_item->getProductId();
        }
        $_product = Mage::getModel('catalog/product')->load($_item->getProductId());
        $orderItemId = $_item->getOrderItemId();
        $minQty = $_item->getQty()*1;
        if($minQty < $item->getQty())
            $minQty = $item->getQty()*1;
        $checkAvailable =  Mage::helper('inventory/warehouse')->checkTheFirstWarehouseAvailableProduct($productId,$minQty);
        $product=Mage::getModel('catalog/product')->load($productId);
        $productType=$product->getTypeID();
    ?>
    <?php $this->setPriceDataObject($_item) ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $this->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr>
                <td><div class="option-label"><?php echo $attributes['option_label'] ?></div></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td class="last">&nbsp;</td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr class="<?php echo (++$_index==$_count && !$_showlastRow)?'border':'' ?>">
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
            <td><h5 class="title"><?php echo $this->htmlEscape($_item->getName()) ?></h5>
                <div>
                    <strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong>
                    <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($_item->getSku()))); ?>
                </div>
            </td>
        <?php else: ?>
            <td><div class="option-value"><?php echo $this->getValueHtml($_item)?></div></td>
        <?php endif; ?>
        <td class="a-center"><img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getSmallImage()); ?>" width="90" height="90" /></td>
        <td>
            <?php if ($this->isShipmentSeparately($_item)): ?>
                <?php if(Mage::getStoreConfig('inventory/dropship/enable')): ?>                    
                    <?php echo Mage::getBlockSingleton('inventorydropship/items')->getColumnHtml($_item, 'qty') ?>
                <?php else: ?>                    
                    <?php echo $this->getColumnHtml($_item, 'qty') ?>
                <?php endif ?>
                <?php //echo $this->getColumnHtml($_item, 'qty') ?>                
            <?php else: ?>                
                &nbsp;
            <?php endif; ?>
        </td>
        <td>
            <?php if ($this->isShipmentSeparately($_item)): ?>
                <?php //check max qty to ship ?>
                <?php $maxQty = $_item->getQty()*1 ?>
                <?php 
                    if(Mage::getStoreConfig('inventory/dropship/enable')){
                        $allDropships = Mage::getModel('inventorydropship/inventorydropship')
                                                            ->getCollection()
                                                            ->addFieldToFilter('order_id',$this->getRequest()->getParam('order_id'))
                                                            ->addFieldToFilter('status',array('in'=>array('3','4','6')));
                        $allDropshipIds = array();
                        foreach($allDropships as $dropship)
                            $allDropshipIds[] = $dropship->getId();
                        $dropshipProductNumber = 0;
                        $dropshipProducts = Mage::getModel('inventorydropship/inventorydropshipproduct') 
                                                            ->getCollection()
                                                            ->addFieldToFilter('dropship_id',array('in'=>$allDropshipIds))
                                                            ->addFieldToFilter('item_id',$_item->getOrderItemId());
                        foreach($dropshipProducts as $dropshipProduct)
                            $dropshipProductNumber += $dropshipProduct->getQtyApprove() - $dropshipProduct->getQtyShipped();
                        $maxQty -= $dropshipProductNumber;
                    }
                ?>
                <input type="hidden" value="<?php echo $maxQty ?>" id="shipment[maxitems][<?php echo $_item->getOrderItemId() ?>]" />
                <input type="text" class="input-text" id="shipment[items][<?php echo $_item->getOrderItemId() ?>]" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $maxQty*1 //$_item->getQty()*1 ?>" />
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <!------------------------------------------------------------------------------------------------->
        <?php if ($this->isShipmentSeparately($_item)): ?>
            
            <?php if($productType != 'bundle'): ?>
                <td><div id="show_select_warehouse_supplier_<?php echo $_item->getOrderItemId() ?>_<?php echo $productId ?>"><?php echo Mage::helper('inventory/warehouse')->selectboxWarehouseShipmentByPid($productId,$_item->getQty(),$_item->getOrderItemId()); ?></div></td>
            <?php else: ?>
                <td><div id="show_select_only_supplier_<?php echo $_item->getOrderItemId() ?>_<?php echo $productId ?>"><?php echo Mage::helper('inventory/warehouse')->selectboxWarehouseShipmentByPid($productId,$_item->getQty(),$_item->getOrderItemId()); ?></div></td>                
                <script type="text/javascript">
                    if($('show_select_only_warehouse_<?php echo $_item->getOrderItemId() ?>_<?php echo $productId ?>')){
                        $('show_select_only_warehouse_<?php echo $_item->getOrderItemId() ?>_<?php echo $productId ?>').innerHTML = '';
                    }
                    if($('show_select_only_supplier_<?php echo $_item->getOrderItemId() ?>_<?php echo $productId ?>')){
                        $('show_select_only_supplier_<?php echo $_item->getOrderItemId() ?>_<?php echo $productId ?>').innerHTML = '';
                    }
                </script>
            <?php endif; ?>
            <?php if($productType != 'bundle'): ?>    
                <?php if($checkAvailable == true): ?>
                    <td class="a-center last"><span id="span-shipment[items][<?php echo $_item->getOrderItemId() ?>]">
                        <img src="<?php echo Mage::getDesign()->getSkinUrl('images/success_msg_icon.gif', array('_area'=>'adminhtml')); ?> "/>
                        <input type="hidden" id="check-shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="1" />
                    </span></td>
                    <script>
                        Event.observe($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"),'change', function(){
                            var productId = '<?php echo $productId ?>';
                            var orderid = '<?php echo $orderId; ?>';
                            var warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                            var qtyToShip = $$('[name="shipment[items][<?php echo $_item->getOrderItemId() ?>]"]')[0].value ;
                            var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                            //alert('*'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);
                            checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                            });

                        Event.observe($("shipment[items][<?php echo $_item->getOrderItemId() ?>]"),'keyup', function(){   
                            var productId = '<?php echo $productId ?>';
                            var orderid = '<?php echo $orderId; ?>';
                            var warehouseId = '';
                            if($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"))
                                var warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                            var qtyToShip = $$('[name="shipment[items][<?php echo $_item->getOrderItemId() ?>]"]')[0].value ;
                            var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                            //alert('*'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);
                            if(warehouseId)
                                checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                            });
                    </script>
                <?php else: ?>
                    <?php $warehouseId = Mage::helper('inventory/warehouse')->getFirstWarehouseHaveMostOfAProduct($productId); ?>
                    <td class="a-center last">
                       <span id="span-shipment[items][<?php echo $_item->getOrderItemId() ?>]">
                           <img src="<?php echo Mage::getDesign()->getSkinUrl('images/error_msg_icon.gif', array('_area'=>'adminhtml')); ?> "/>
                           <input type="hidden" id="check-shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="0" />
                           <button type="button"  onclick="tinyboxopen('<?php echo $_item->getOrderItemId() ?>','<?php echo $productId; ?>','<?php echo "warehouse-shipment[items][".$_item->getOrderItemId()."]";//$warehouseId ?>','<?php echo $minQty; ?>','<?php echo $orderId; ?>');"  class="scalable" type="button" ><span><?php echo  $this->helper('inventory')->__('Need to Receive Stock.'); ?></span></button>
                       </span>
                   </td>
                    <script> var checkExistNeedTransfer = true;</script>
                    <script>
                        if($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"))
                            Event.observe($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"),'change', function(){
                                var productId = '<?php echo $productId ?>';
                                var orderid = '<?php echo $orderId; ?>';
                                var warehouseId = '';
                                if($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"))
                                    warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                                var qtyToShip = $$('[name="shipment[items][<?php echo $_item->getOrderItemId() ?>]"]')[0].value ;
                                var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                                //alert('**'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);
                                checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                            });

                        Event.observe($("shipment[items][<?php echo $_item->getOrderItemId() ?>]"),'keyup', function(){                
//                            if($("shipment[items][<?php echo $_item->getOrderItemId() ?>]").value > $("shipment[maxitems][<?php echo $_item->getOrderItemId() ?>]").value)
//                                $("shipment[items][<?php echo $_item->getOrderItemId() ?>]").value = $("shipment[maxitems][<?php echo $_item->getOrderItemId() ?>]").value;
                            
                            if($("shipment[items][<?php echo $_item->getOrderItemId() ?>]") && $("shipment[maxitems][<?php echo $_item->getOrderItemId() ?>]"))
                                if(parseInt($("shipment[items][<?php echo $_item->getOrderItemId() ?>]").value) > parseInt($("shipment[maxitems][<?php echo $_item->getOrderItemId() ?>]").value))
                                    $("shipment[items][<?php echo $_item->getOrderItemId() ?>]").value = $("shipment[maxitems][<?php echo $_item->getOrderItemId() ?>]").value;
                            
                            var productId = '<?php echo $productId ?>';
                            var orderid = '<?php echo $orderId; ?>';
                            var warehouseId = '';
                            if($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"))
                                warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                            var qtyToShip = $$('[name="shipment[items][<?php echo $_item->getOrderItemId() ?>]"]')[0].value ;
                            var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                            //alert('**'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);
                            if(warehouseId)
                                checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                        });
                    </script>
                <?php endif; ?>
            <?php else: ?>
                <td class="a-center last">
                    <span id="span-shipment-dropship[items][<?php echo $_item->getOrderItemId() ?>]">                        
                    </span>
                </td>
            <?php endif; ?>
      <!------------------------------------------------------------------------------------------------>      
        <?php else: ?> <!-- end $this->isShipmentSeparately($_item) == true -->
            <?php if($productType != 'bundle'): ?>
                <td><div id="show_select_warehouse_supplier_<?php echo $_item->getOrderItemId() ?>_<?php echo $productId ?>"><?php echo Mage::helper('inventory/warehouse')->selectboxWarehouseShipmentByPid($productId,$_item->getQty(),$_item->getOrderItemId()); ?></div></td>
                <?php $parentItemId = $_item->getOrderItem()->getParentItem()->getId(); ?>
                <?php if($checkAvailable == true): ?>
                <td class="a-center last"><span id="span-shipment[items][<?php echo $_item->getOrderItemId() ?>]">
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('images/success_msg_icon.gif', array('_area'=>'adminhtml')); ?> "/>
                    <input type="hidden" id="check-shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="1" />
                </span></td>
                <script>
                    Event.observe($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"),'change', function(){                                                                        
                        var productId = '<?php echo $productId ?>';
                        var orderid = '<?php echo $orderId; ?>';
                        var warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                        var qtyToShip = $$('[name="shipment[items][<?php echo $parentItemId ?>]"]')[0].value ;
                        var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                        //alert('***'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);
                        checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                        });
                    Event.observe($("shipment[items][<?php echo $parentItemId ?>]"),'keyup', function(){ 
                        if($("shipment[items][<?php echo $parentItemId ?>]") && $("shipment[maxitems][<?php echo $parentItemId ?>]"))
                            if(parseInt($("shipment[items][<?php echo $parentItemId ?>]").value) > parseInt($("shipment[maxitems][<?php echo $parentItemId ?>]").value))
                                $("shipment[items][<?php echo $parentItemId ?>]").value = $("shipment[maxitems][<?php echo $parentItemId ?>]").value;

                        var productId = '<?php echo $productId ?>';
                        var orderid = '<?php echo $orderId; ?>';
                        var warehouseId = '';
                        var qtyToShip = '';                        
                        if($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"))
                            var warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                        if($$('[name="shipment[items][<?php echo $parentItemId ?>]"]')[0])
                            var qtyToShip = $$('[name="shipment[items][<?php echo $parentItemId ?>]"]')[0].value ;
                        var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                        //alert('*'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);
                        if(warehouseId)
                            checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                        });
                </script>
                <?php else: ?>
                    <?php $warehouseId = Mage::helper('inventory/warehouse')->getFirstWarehouseHaveMostOfAProduct($productId); ?>
                    <td class="a-center last">
                        <span id="span-shipment[items][<?php echo $_item->getOrderItemId() ?>]">
                            <img src="<?php echo Mage::getDesign()->getSkinUrl('images/error_msg_icon.gif', array('_area'=>'adminhtml')); ?> "/>
                            <input type="hidden" id="check-shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="0" />
                            <button type="button"  onclick="tinyboxopen('<?php echo $_item->getOrderItemId() ?>','<?php echo $productId; ?>','<?php echo "warehouse-shipment[items][".$_item->getOrderItemId()."]";//$warehouseId ?>','<?php echo $minQty; ?>','<?php echo $orderId; ?>');"  class="scalable" type="button" ><span><?php echo  $this->helper('inventory')->__('Need to Receive Stock'); ?></span></button>
                        </span>
                    </td>
                    <script>checkExistNeedTransfer = true;</script>
                    <script>
                        Event.observe($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"),'change', function(){                                                        
                            var productId = '<?php echo $productId ?>';
                            var orderid = '<?php echo $orderId; ?>';                            
                            var warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                            var qtyToShip = $$('[name="shipment[items][<?php echo $parentItemId ?>]"]')[0].value ;
                            var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                            //alert('****'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);                            
                            checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                        });
                        Event.observe($("shipment[items][<?php echo $parentItemId ?>]"),'keyup', function(){   
                            if($("shipment[items][<?php echo $parentItemId ?>]") && $("shipment[maxitems][<?php echo $parentItemId ?>]"))
                                if(parseInt($("shipment[items][<?php echo $parentItemId ?>]").value) > parseInt($("shipment[maxitems][<?php echo $parentItemId ?>]").value))
                                    $("shipment[items][<?php echo $parentItemId ?>]").value = $("shipment[maxitems][<?php echo $parentItemId ?>]").value;

                            var productId = '<?php echo $productId ?>';
                            var orderid = '<?php echo $orderId; ?>';
                            var warehouseId = '';
                            var qtyToShip = '';
                            if($("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]"))
                                var warehouseId = $("warehouse-shipment[items][<?php echo $_item->getOrderItemId() ?>]").value;
                            var qtyToShip = $$('[name="shipment[items][<?php echo $parentItemId ?>]"]')[0].value ;
                            var orderItemId = '<?php echo $_item->getOrderItemId() ?>';
                            //alert('*'+'-----'+warehouseId+'----..'+productId+'----..'+qtyToShip+'----..'+orderItemId+'----..'+orderid+'----..'+qtyToShip);
                            if(warehouseId)
                                checkStatusAvailableAOrderItemByEvent(warehouseId,productId,qtyToShip,orderItemId,orderid,qtyToShip);
                        });    
                    </script>
                <?php endif; ?>
            <?php else: ?>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            <?php endif; ?>
        <?php endif; ?>
      <!------------------------------------------------------------------------------------------------->          
    </tr>
<?php endforeach; ?>
<?php if($_showlastRow): ?>
    <tr class="border">
        <td>
            <?php if ($this->getOrderOptions($_item->getOrderItem())): ?>
                <dl class="item-options">
                <?php foreach ($this->getOrderOptions($_item->getOrderItem()) as $option): ?>
                    <dt><?php echo $option['label'] ?></dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?php echo $option['value'];?>
                    <?php else: ?>
                        <?php echo Mage::helper('core/string')->truncate($option['value'], 55, '', $_remainder);?>
                        <?php if ($_remainder):?>
                            ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                            <script type="text/javascript">
                            $('<?php echo $_id ?>').hide();
                            $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                            $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                            </script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
                        <?php else: ?>
                &nbsp;
                        <?php endif; ?>
            <?php echo $this->htmlEscape($_item->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>