<?php
	$iconurl = Mage::getBaseurl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "images/";
	//echo $count;
?>
<div class="shopbycategory-container">
<div class="shopbycategory-content">
<div class="shopbycategory-header">
SHOP BY CATEGORY
</div>
<div class="shopbycategory-item-container">


	<?php 

		// $attribute_code = "unilab_segment";
		// $attribute_details = Mage::getSingleton("eav/config")->getAttribute("catalog_product", $attribute_code); 
		// $data = $attribute_details->getSource()->getAllOptions(false); 
		// foreach($data as $_item):
		// 	$value = $_item['value'];
		// 	$label = $_item['label'];

		$shopbyid = Mage::getStoreConfig('oneshop/oneshopsettings/shopbycategory');
		
		$category = Mage::getModel('catalog/category')->load($shopbyid); //SHOP BY Category id
		$subcategories = $category->getChildrenCategories();

		if (count($subcategories) > 0){
    	foreach($subcategories as $subcategory){

    	$categoryname 	= $subcategory->getName();
    	$categoryurl 	= $subcategory->getUrl();
        $categoryimage 	= Mage::getBaseUrl('media').'catalog/category/'.$subcategory->getImage();


?>
<div class="category-container">
	<div class="category-item">
		<!-- <img  src="<?php echo $iconurl.$label?>.jpg"> -->
		<img  src="<?php echo $categoryimage; ?>">
		<span class="cat-label"><a href="<?php echo $categoryurl; ?>"><?php echo $categoryname; ?></a></span>	
	</div>
</div>
		<?php }
	}//endforeach;?>
</div>
</div>
</div>
