<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head head-adminhtml-inventory">
                <?php if(Mage::app()->getRequest()->getActionName()=='notice'): ?>
                <?php echo $this->__('Backorder Request Reports');?>
                <?php endif; ?>
                </h3></td>
        </tr>
    </tbody></table>
</div>