<div id="cancelPrescription" style="width:300px;height:200px;margin-top:20px;margin-bottom:10px;"> 
	<h3><?php echo $this->__("You have indicated that you do not have a prescription.");?></h3>
	<p><?php echo $this->__("For your safety, we can only process orders with a prescription.");?></p>	
	<p style="text-align: center;margin: 0 auto;width: 224px;">	
		<input type="button" name="close" class="button" id="btnCancelPrescription" value="<?php echo $this->__("Proceed");?>"/>
		<input type="button" name="close" class="button" id="btnCancelPrescriptionRemove" value="<?php echo $this->__("Cancel");?>"/>
	</p>
</div> 
<div style="display:none;" id="form_wrapper_cancelled"></div>