<div class="row heymom-footer">
	<div class="social-media">
		Follow us on 
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/default/heymom/images/fb.png">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/default/heymom/images/tweeter.png">
		| Contact us
	</div>
	<div class="all-rights-reserved">
		<span>2015 © heymom.com.ph All Rights Reserved.</span> 
	</div>
	<div class="clear"></div>
</div>