  
	   <table cellspacing="0" cellpadding="0" border="0" width="650" style="margin: 0 auto";>
			<tr>
				<th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Payment Instructions:</th>
			</tr>
			
			<tr>
				<td valign="top" style="font-size:12px; padding:7px 9px 9px 9px; border-left:1px solid #EAEAEA; border-bottom:1px solid #EAEAEA; border-right:1px solid #EAEAEA;">
	  
	  <?php
			echo Mage::getStoreConfig('payment/perapal/paymentinstructions');
      ?>
				</td>
			</tr>
		</table>

	