<div id="remember-me-popup" class="remember-me-popup" style="display:none;">
    <div class="remember-me-popup-body">
        <p><?php echo $this->__("Checking &quot;Remember Me&quot; will let you access your shopping cart on this computer when you are logged out");?></p>
        <a href="javascript:void(0);" style="width:52px;background:#FB3561;color:#FFFFFF;" class="remember-me-popup-close button" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleRememberMepopup(e){
        if($('remember-me-popup')){
            $('remember-me-popup').setStyle({'top' : e.pointerY() + 'px'}).toggle();
        }
        Event.stop(event);
    }

    document.observe("dom:loaded", function() {
        new Insertion.Bottom($$('body')[0], $('remember-me-popup'));

        $$('.remember-me-popup-close').each(function(element){
            Event.observe(element, 'click', toggleRememberMepopup);
        })
        $$('#remember-me-box a').each(function(element) {
            Event.observe(element, 'click', toggleRememberMepopup);
        });
    });
//]]>
</script>
