<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>

<style>
    #modal_wrapper
    {
        display:none;
    }
    .mod_header h1, .login_form, .mod_footer
    {
        text-align: left;
    }

    div#modal_wrapper{
        /* top: 30%; */
        position: fixed;
    }
</style>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        
        <?php //$xQty = ($this->getProductDefaultQty() * 1) == 0 ? 1 : $this->getProductDefaultQty() * 1; ?>
        
        <?php $xQty = $_product->getunilab_moq() * 1; ?>

        <div id="modal_wrapper">
            <div class="mod_header">
                <h1 class="header_title">Invalid Quantity</h1>
            </div>
            <div class="mod_body">  
                <div class="login_form">
                    <label class="message"></label>
                </div>      
                        
            </div>
            
            <div class="mod_footer">
                <div class="save_empinfo">
                    <div class="form_group">
                        <button type="button" title="Add to Cart" class="button btn-cart btnok" >
                            <span><span>Ok</span></span>
                        </button>                   
                    </div>
                </div>  
            </div>  
        </div> 
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $xQty ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty numbersOnly" />
        <?php endif; ?>
        <?php if($_product->getUnilabRx()):?>
            <button type="button" id="btnAddToCart" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.askPrescription(this);"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php else:?>
            <button type="button" id="btnAddToCart"  title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this);"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php endif;?>
        <?php  
         if( $_product->getAttributeSetId() == 12) //OTC Attribute Set
            $this->getChildHtml('', true, true); ?>
    </div>
    <script>
        var addtocart = document.getElementById("qty");

        addtocart.addEventListener("keypress", function(event) {
            if (event.keyCode == 13){
                jQuery("#btnAddToCart").trigger("click");
                event.preventDefault();
                return;
            }
        });
    </script>
<?php endif; ?>
 <script>
        
            jQuery(document).ready(function (){
            
            
                jQuery('#modal_wrapper').append('<div class="black_back"></div>');  
            
                jQuery('[name=qty]').change(function (){
                    var ab = <?php echo $_product->getunilab_antibiotic() == 1 ?  $_product->getunilab_antibiotic() : 0;?>;
                    var moq = <?php echo $xQty ?>;
                    
                    var qtyVal = jQuery(this).val();
                    
                    if (qtyVal % moq == 0 && ab == 0)
                    {
                        jQuery('#btnAddToCart').removeAttr('disabled');
                        //jQuery("#btnAddToCart").trigger("click");
                    }
                    else if(qtyVal >= moq && ab == 1)
                    {
                        jQuery('#btnAddToCart').removeAttr('disabled'); 
                    }
                    else
                    {
                    
                        jQuery('#modal_wrapper').fadeIn();
                        if(ab == 1)
                        {
                            jQuery('.message').html('We’re sorry. We cannot process the quantity you requested. Kindly enter a quantity ' + moq + ' or more. Thank you.');
                        }
                        else
                        {
                            jQuery('.message').html('We’re sorry. We cannot process the quantity you requested. Kindly enter a quantity divisible by ' + moq + '. Thank you.');
                        }
                        
                        
                        jQuery('#btnAddToCart').attr('disabled','true');
                        
                    }                   
                    
                });
                
                
                jQuery('.btnok').click(function (){
                
                    jQuery('#modal_wrapper').fadeOut();
                    
                    jQuery('[name=qty]').focus();
                    
                    jQuery('[name=qty]').val(<?php echo $xQty ?>);
                    
                    jQuery('#btnAddToCart').removeAttr('disabled');
                    

                
                });
            
            
            });
            
        
        </script>
<script>
    jQuery('.numbersOnly').keyup(function () { 
        this.value = this.value.replace(/[^0-9\.]/g,'');
    });
</script>
  