<div class="cart">

    
    <!-- <div class="page-title title-buttons"> 

        <?php if(!$this->hasError()): ?>

        <ul class="checkout-types">

        <?php foreach ($this->getMethods('top_methods') as $method): ?>

            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>

            <li><?php echo $methodHtml; ?></li>

            <?php endif; ?>

        <?php endforeach; ?>

        </ul>

        <?php endif; ?>

    </div> -->

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <?php echo $this->getChildHtml('form_before') ?>

    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">

        <fieldset>

            <table id="shopping-cart-table" class="data-table cart-table">

                <col width="1" />

                <col />

                <col width="1" /> 

                <col /> 

            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

                <col width="1" />

            <?php endif; ?>

            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

                <col width="1" />

            <?php endif; ?>

                <col width="1" />

            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

                <col width="1" />

            <?php endif; ?>

            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

                <col width="1" />

            <?php endif; ?>

                <col width="1" />



            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>

                <thead>

                    <tr>

					

                        <th class="a-center" rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Product Item(s)') ?></th>

                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php //echo $this->__('Name') ?>

                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php //echo $this->__('Prescription') ?>

                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Quantity') ?></th>

                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Price') ?></th>

                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Total') ?></th>

                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>

                    </tr>

                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>

                    <tr>

                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>

                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>

                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>

                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>

                    </tr>

                    <?php endif; ?>

                </thead>

               

                <tbody>

		

                <?php foreach($this->getItems() as $_item): ?>

	

                    <?php echo $this->getItemHtml($_item) ?>

                <?php endforeach ?>

                </tbody>

                <tfoot>

                    <tr>

                        <td colspan="50" class="a-right">

                           <button type="button" title="<?php echo $this->__('continue shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><?php echo $this->__('Continue Shopping') ?><span> </span></span></button>   

                            <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>

                            <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><?php echo $this->__('Clear Shopping Cart'); ?></span></button>

                            <!--[if lt IE 8]>

                            <input type="hidden" id="update_cart_action_container" />

                            <script type="text/javascript">

                            //<![CDATA[

                                Event.observe(window, 'load', function()

                                {

                                    // Internet Explorer (lt 8) does not support value attribute in button elements

                                    $emptyCartButton = $('empty_cart_button');

                                    $cartActionContainer = $('update_cart_action_container');

                                    if ($emptyCartButton && $cartActionContainer) {

                                        Event.observe($emptyCartButton, 'click', function()

                                        {

                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');

                                            $cartActionContainer.setAttribute('name', 'update_cart_action');

                                            $cartActionContainer.setValue('empty_cart');

                                        });

                                    }



                                });

                            //]]>

                            </script>

                            <![endif]-->

                        </td>

                    </tr>

                </tfoot>				

            </table>

            <script type="text/javascript">decorateTable('shopping-cart-table')</script>

        </fieldset>

    </form>

    <div class="cart-collaterals">

            <div class="collat-wrap">

                <div class="grid_4"><?php echo $this->getChildHtml('coupon') ?></div>

               <?php /* <div class="grid_4"><?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?></div>*/?>

                <div class="totals grid_4">

                    <?php echo $this->getChildHtml('totals'); ?> 

                    

                </div>

                <div style="float:right">

             

                    <button type="button" title="<?php echo $this->__('checkout') ?>" class="button btnCheckout" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('checkout') ?></span></span>

                    </button>     

                </div>

            </div>

			<div class="crosssell-wrap">

                <?php echo $this->getChildHtml('crosssell') ?>

            </div>

    </div>

	

</div>



<script type="text/javascript">

	//<![CDATA[ 

	

		var confirm_prescription_html = ''; 

		var prescription_response	  = '';

		

		Event.observe(window, 'load', function()

		{ 

			var edit_prescription_element = $$("a.edit_prescription");

				edit_prescription_element.each(function(elm){

					Event.observe(elm,'click',function(){ 

							jQuery.fancybox.showLoading(); 

							var prescription_edit_url  = '<?php echo $this->getUrl('prescription/index/editPrescription');?>'; 

							var request = new Ajax.Request(prescription_edit_url, {	

								parameters: {'item_id': elm.rel},

								onSuccess: function(transport){ 		  						

									if(transport.status == 200)	{

										var response = transport.responseText.evalJSON();										 	

											prescriptionControls(response); 	 

									}

								},

								onFailure: '',

								onComplete: function(){					

									jQuery.fancybox.hideLoading();

								}

							}); 

					}); 

				});

				

				var add_prescription_element = $$("a.add_prescription");

				add_prescription_element.each(function(elm){

					Event.observe(elm,'click',function(){ 

							jQuery.fancybox.showLoading(); 

							var prescription_add_url  = '<?php echo $this->getUrl('prescription/index/editPrescription');?>'; 

							var request = new Ajax.Request(prescription_add_url, {	

								parameters: {'item_id': elm.rel},

								onSuccess: function(transport){ 		  						

									if(transport.status == 200)	{

										var response = transport.responseText.evalJSON();										 	

											prescriptionControls(response); 	 

									}

								},

								onFailure: '',

								onComplete: function(){					

									jQuery.fancybox.hideLoading();

								}

							}); 

					}); 

				});

		 }); 

		 

		 var prescriptionControls = function(response)

			{		

				showDialog(response.prescription_dialog);

				jQuery("#cancel_prescription").click(function(){

					jQuery.fancybox.close();

				});	 

				

				prescription_response     = response; 	 				 

				confirm_prescription_html = response.confirm_dialog; 			 

			}

		 var showDialog = function(_content)

			{	

				jQuery.fancybox({content: _content,

								 closeBtn: false,

								 closeClick: false,

								 helpers: { overlay : {closeClick : false,

													  locked:	   true}}

								}); 

			}

	//]]> 

</script>