<!--div class="block block-account" >
    <div class="block-title">
        <strong><span><?php echo $this->__("Information");?></span></strong>
    </div>
    <div class="block-content">
        <ul class="information">
			<li class="current"><strong><a title="<?php echo $this->__("About Us");?>" href="<?php echo $this->getUrl("aboutus");?>"><?php echo $this->__("About Us");?></a></strong></li>
			<li class="current"><strong><a title="<?php echo $this->__("Contact Us");?>" href="<?php echo $this->getUrl("contacts");?>"><?php echo $this->__("Contact Us");?></a></strong></li>
			<li class="current"><strong><a title="<?php echo $this->__("Terms And Condition");?>" href="<?php echo $this->getUrl("terms-and-condition");?>"><?php echo $this->__("Terms & Conditions");?></a></strong></li>
			<li class="current"><strong><a title="<?php echo $this->__("Privacy Policy");?>" href="<?php echo $this->getUrl("privacy-policy");?>"><?php echo $this->__("Privacy Policy");?></a></strong></li> 
		</ul>
	</div>
</div-->