<?php

$customer = Mage::getSingleton('customer/session')->getCustomer();

$defaultBilling = $customer->getDefaultBillingAddress();

?>

<div class="shipping_wrapper">
	<div class="heading">
		<div class="cls_number">1.a</div>
		<h1 class="cls_header">Billing Address</h1>
	</div>
	<div class="cls_body">
		<ul class="form-list">
		<form action="" id="billing_address_form">
			<li class="wide">
				<label for="billing-address-select">Select a Billing Address</label>
				<div class="input-box">
					<select name="billing_address_id" id="billing_address_id" class="address_select" onchange="selectAddress_billing()" title="Select your Billing Address" autocomplete="off">
						<?php					
							foreach ($customer->getAddresses() as $address) {
								if (!empty($address['entity_id'])):
									$defaultbilling = $customer->getPrimaryBillingAddress()->getId();
									$billingfulladd = $address['firstname'] . " " .$address['lastname'] . ", " . $address['street'] . ", " . $address['city'] . ", " . $address['region'] . ", " . $address['postcode'];
								
									if($address['entity_id'] == $defaultbilling){
									?>
									<option value="<?php echo $address['entity_id']; ?>" selected="selected"><?php echo $billingfulladd; ?></option>
									<?php
										$address_firstname = $address['firstname'];
										$address_lastname = $address['lastname'];
									}else{
									?>
										<option value="<?php echo $address['entity_id']; ?>"><?php echo $billingfulladd; ?></option>
									<?php
									}
								endif;
							}
						?>					
						<option value="0">New address</option> 					
					</select>
				</div>
			</li>

			<input type="hidden" name="billing[emailaddress]" id="emailaddress" value="<?php echo $customer->getEmail(); ?>" >
			<li class="fields">
				<div class="customer-name">
					<div class="name-firstname">
						<label for="billing_firstname" class="required"><em>*</em>First Name</label>
						<div class="input-box">
							<input type="text" id="billing_firstname" name="billing[firstname]" value="<?php echo $address_firstname; ?>" title="First Name" class="input-text required-entry absolute-advice validation-passed" autocomplete="off">
						</div>
					</div>
					<div class="name-lastname">
						<label for="billing_lastname" class="required"><em>*</em>Last Name</label>
						<div class="input-box">
							<input type="text" id="billing_lastname" name="billing[lastname]" value="<?php echo $address_lastname; ?>" title="Last Name" class="input-text required-entry absolute-advice validation-passed" autocomplete="off">
						</div>
					</div>
				</div>
			</li> 
			
			<li class="wide">
				<label for="billing_country_id" class="required"><em>*</em>Country</label>
				<div class="input-box input-box-country billing-country">
					<?php 
					
						$_countries = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false);
						$countryCode = Mage::getStoreConfig('general/country/default');
					?>
					<?php if (count($_countries) > 0): ?>
						<select name="billing[country_id]" id="billing_country_id" class="required-entry absolute-advice" title="Country" autocomplete="off">
							<option value="">-- Please Select --</option>
							<?php foreach($_countries as $_country): ?>
								<?php if ($_country['value'] == $countryCode ): ?>
								<option value="<?php echo $_country['value'] ?>" selected>
									<?php echo $_country['label'] ?>
								</option>
							<?php else: ?>
								<option value="<?php echo $_country['value'] ?>"> 
									<?php echo $_country['label'] ?>
								</option>
							<?php endif; endforeach; ?>
						</select>
					<?php endif; ?>
				</div>
			</li>
			
			<li class="fields telephone-mobile">
				<div class="field-telephone  field-first">
					<label for="billing_postcode" class=" required "><em>*</em>Zip/Postal</label>
					<div class="input-box billing_postcode">
						<input type="text" name="billing[postcode]" id="billing_postcode" value="<?php if(!empty($defaultBilling)): echo $customer->getPrimaryBillingAddress()->getPostcode(); endif; ?>" title="Zip/Postal" class=" input-text required-entry absolute-advice " autocomplete="off">
					</div>
					
				</div>
				<div class="field-mobile  field-last ">
					<label for="billing_region_id" class=" required "><em>*</em>State/Province</label>
					<div class="input-box input-box-country billing-country">
						<select onchange="changeAddressSave(this.checked)" id="billing_region_id" name="billing[region_id]" title="State/Province" class="input-text required-entry absolute-advice validate-select" defaultvalue="" autocomplete="off">
							<?php 

								if(!empty($defaultBilling)):
									$customerregionID = $customer->getPrimaryBillingAddress()->getRegionId();
									echo '<option value="0" >Select address</option>'; 								
								else:
									$customerregionID = 0;
									echo '<option value="0" selected="selected">Select address</option>'; 								
								endif;
								
									$collection = Mage::getModel('directory/region')->getResourceCollection()->addCountryFilter('PH')->load();
									
									foreach($collection as $region) 
									{
										if ($customerregionID == $region['region_id'] ): 
											echo '<option value="'.$region['region_id'].'" selected="selected">'.$region['name'].'</option> ';
										else:
											$regionName = $region['name'];
											echo '<option value="'.$region['region_id'].'" >'.$region['name'].'</option> ';									
										endif;

									}
							?>
						</select>
						<input type="text" id="billing_region" name="billing[region]" value="<?php echo $regionName ?>" title="State/Province" class="input-text required-entry absolute-advice" style="display: none;" autocomplete="off">
					</div>
				</div>
			</li> 	
			<script type="text/javascript">
			jQuery(document).on('change','#billing_region_id', function(){
		

				var data = jQuery(this).val(); 

				jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: data }, function(res){				
					jQuery("#billing_city").html(res);
				});


				if(document.getElementById('billing_use_for_shipping_yes').checked){
					jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: data }, function(res){				
						jQuery("#shipping_city").html(res);
					});
				}
			});
			</script>
			<li class="wide">
					<label for="billing_city" class=" required "><em>*</em>City</label>
			
					
					<div  class="input-box billing_city" id="citylist">	
						<?php 

							$connection = Mage::getSingleton('core/resource')->getConnection('core_read');
							$connection->beginTransaction();
							
							if(!empty($defaultBilling))
							{
								$city			= $customer->getPrimaryBillingAddress()->getCity();
								$provinceid 	= $customer->getPrimaryBillingAddress()->getRegionId();
								
								$qrycities = $connection->select()->from('unilab_cities', array('*')) 
										->where('region_id=?',$provinceid)	
										->order(array('name ASC'));
								$cities = $connection->fetchAll($qrycities);
								
							}

						?>
						<select id="billing_city" name="billing[city]" class="input-text required-entry absolute-advice" title="City" onchange="onchangeBillingSave()">
							<?php										
								echo '<option value="0" selected="selected">Select address</option>'; 
										
									foreach ($cities as $value) 
									{ 
										$cities_id = $value['city_id'];
										$cities_name = $value['name'];
										
										if($cities_name==$city)
										{
											// echo "<option value='$cities_name' selected='selected'>$cities_name</option>";
											echo "<option value='$cities_id' selected='selected'>$cities_name</option>";
										}
										else
										{
											echo "<option value='$cities_id'>$cities_name</option>";
										}
									}	
							?>
						</select>
					</div>
			</li> 

			<li class="wide">
				<label for="billing_street1" class=" required "><em>*</em>Address</label>
				<div class="input-box">
					<input type="text" title="Street Address" name="billing[street][]" id="billing_street1" value="<?php if(!empty($defaultBilling)): echo $customer->getPrimaryBillingAddress()->getStreet(1); endif; ?>" class=" input-text required-entry absolute-advice " autocomplete="off" onchange="onchangeBillingSave()">
				</div>
				<br/>
			</li>
					
			
			<li class="fields">
				<div class="customer-name" style="">
					<div class="field-telephone">
						<label for="billing_telephone" class="">Telephone</label><span class="err_mssg" style="color:red; display:none;"><em>This field is required</em></span>
						<div class="input-box">
						<input type="text" name="billing[telephone]" id="billing_telephone" value="<?php if(!empty($defaultBilling)):  echo $customer->getPrimaryBillingAddress()->getTelephone(); endif; ?>" title="Telephone" class=" input-text required-entry absolute-advice " autocomplete="off">
						</div>
					</div>
					<div class="field-mobile">
						<label for="billing_mobile" class="required"><em>*</em>Mobile</label><span class="err_mssg_mobile" style="color:red; display:none;"><em>This field is required</em></span>
						<div class="input-box">
							<input type="text" name="billing[mobile]" id="billing_mobile" value="<?php if(!empty($defaultBilling)):  echo $customer->getPrimaryBillingAddress()->getMobile(); endif; ?>" title="Mobile" class=" input-text required-entry absolute-advice " autocomplete="off" onchange="onchangeBillingSave()">
						</div>
					</div>
				</div>
			</li>
			
			<li id="billing_siab" class="control control-siab" style="display:none;">
				<!-- <span class="save_address_book"><a href="#">Save in address book</a></span>
				<input type="checkbox" name="billing[save_in_address_book]"  id="billing_save_in_address_book" class="checkbox" autocomplete="off"> -->
				<!-- <label for="billing_save_in_address_book">Save in address book</label> -->
				
				<input type="checkbox" name="billing[save_in_address_book]"  id="billing_save_in_address_book" class="checkbox" value="0">
				<span style="color:red; font-size: 11px; position: relative; top:-10px;">* Required Fields</span><br style="display: block;"/>
				<span class="bill_address" id="billing_save_in_address_book_yes" style="position:relative; top:0px;">Save in address book</span>


			</li>

			<?php if (Mage::getStoreConfig('rracheckoutsection/rracheckoutgrounp/shipaddressbook') > 0):	?>
			
			<?php endif; ?>
			
			<?php if (Mage::getStoreConfig('rracheckoutsection/rracheckoutgrounp/shiptoaddress') > 0):	?>
				
 				<li class="control control-stta">
 					<!-- <span style="color:red; font-size: 11px; position: relative; top:10px;">* Required Fields</span><br style="display: block;"/> -->
 					<span class="ship_address">Ship to this address</span>
					<input type="checkbox" name="billing[use_for_shipping]" id="billing_use_for_shipping_yes" value="<?php if (Mage::getStoreConfig('rracheckoutsection/rracheckoutgrounp/shiptoaddress') == 2) echo 1;	?>" title="Ship to this address" <?php if (Mage::getStoreConfig('rracheckoutsection/rracheckoutgrounp/shiptoaddress') == 2) echo 'checked';	?> onclick="changeAddressMode(this.checked)" class="radio" autocomplete="off">
					<label for="billing_use_for_shipping_yes">Ship to this address</label>
				</li>
				
			<?php else: ?>		
				<!-- <span style="color:red; font-size: 11px;">* Required Fields</span><br style="display: block;"/> -->
				<input type="hidden" name="billing[use_for_shipping]" id="billing_use_for_shipping_yes" value="1" title="Ship to this address" >
			<?php endif; ?>
			</form>			
			</ul>
		</div>
</div>

<script type="text/javascript">

jQuery('#billing_save_in_address_book_yes').click(function(){

	if(confirm('Do you want to save your billing address?')){
		jQuery("#billing_save_in_address_book").click();
		jQuery("#billing_save_in_address_book").val(1);
	}

});

</script>


<script>

	function check2(state_id,city_id)
	{		
	
		var array_state ='<?php $stateprovince2 = Mage::getStoreConfig('payment/cashondelivery/stateprovince');
							$default_state = '';
							$stateprovince2 = explode(',', $stateprovince2);

							foreach($stateprovince2 as $stateprovince){
								$default_state .= $stateprovince .","; 
							} 
							echo substr($default_state,0,-1); ?>';



		var array_city ='<?php $city2 = Mage::getStoreConfig('payment/cashondelivery/city');
							$default_city = ''; 
							$city2 = explode(',', $city2);
							foreach($city2 as $city){ 
									$default_city .= $city .","; } 
							echo substr($default_city,0,-1); ?>';

   	
		var splitObj = array_state.split(","); 
		var splitObj2 = array_city.split(",");
		

		if(jQuery.inArray(state_id, splitObj) !=-1 && jQuery.inArray(city_id, splitObj2) !=-1){
			jQuery('#cashondelivery').attr('disabled', false);
			jQuery("label[for='p_method_cashondelivery']").attr('disabled', false);

		}else{
			jQuery('#cashondelivery').attr('disabled', true);
			jQuery('#cashondelivery').removeAttr("checked");
			jQuery("#cashondelivery_name").css('display', 'none');

		}
	}

	function address(){
		var bill_fname = jQuery('#billing_firstname').val();
			jQuery('#shipping_firstname').val(bill_fname);

			var bill_lname = jQuery('#billing_lastname').val();
			jQuery('#shipping_lastname').val(bill_lname);

			var bill_country = jQuery('#billing_country_id').val();
			jQuery('#shipping_country_id').val(bill_country);

			var bill_postcode = jQuery('#billing_postcode').val();
			jQuery('#shipping_postcode').val(bill_postcode);

			var billing_region = jQuery('#billing_region_id').val();
			jQuery('#shipping_region_id').val(billing_region);

			var bill_city = jQuery('#billing_city').val();
			jQuery('#shipping_city').val(bill_city);
			
			var bill_street = jQuery('#billing_street1').val();
			jQuery('#shipping_street1').val(bill_street);

			var bill_tel = jQuery('#billing_telephone').val();
			jQuery('#shipping_telephone').val(bill_tel);

			var bill_mobile = jQuery('#billing_mobile').val();
			jQuery('#shipping_mobile').val(bill_mobile);
	}


	function selectAddress_billing()
	{
	
		var addID = jQuery('#billing_address_id').val();		

		jQuery.post( '<?php echo Mage::getBaseUrl();?>rracheckout/address/addressbill',{ 
			addressID: addID
			},
			function (addressData)
			{
			var dataobj = jQuery.parseJSON(addressData)
			if (dataobj.success == true)
			{
				jQuery('#billing_firstname').val(dataobj.firstname);
				jQuery('#billing_lastname').val(dataobj.lastname);
				
				jQuery('#billing_country_id').val(dataobj.country_id);
				jQuery('#billing_postcode').val(dataobj.postcode);				

				jQuery('#billing_telephone').val(dataobj.telephone);
				jQuery('#billing_street1').val(dataobj.street);
				
				jQuery('#billing_region_id').val(dataobj.region_id);
				jQuery('#billing_region').val(dataobj.region);

				jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/webuiltthiscity', {region_id: dataobj.region_id, cityval: dataobj.city}, function(res){				
					jQuery("#billing_city").html(res);
				});

				jQuery('#billing_city').val(dataobj.city);

				if(document.getElementById('billing_use_for_shipping_yes').checked) {
					check2(dataobj.region_id, dataobj.city);

					address();
					jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: dataobj.region_id, city_id: dataobj.city}, function(res){			
						jQuery("#shipping_city").html(res);
					});

					setTimeout(function(){
						jQuery('input[name=shippingmethod').prop('checked', true).trigger('click');
				
					}, 2000);
				}
				
				
				var paymentdata = jQuery("#billing_address_form").serialize();
				
				jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveBilling/', 
			
					paymentdata,

				function (paymentdataret)
				{
					var dataobj = jQuery.parseJSON(paymentdataret);
					
					if(dataobj.success == true)
					{
						jQuery('#amt_'+dataobj.carrier_code+'').html(dataobj.carrier_method_title + ' - ' + dataobj.shippingrate);
						jQuery('.shipping_name').html(dataobj.carrier_title + ' - ' + dataobj.carrier_method_title);
						jQuery('.shipping_amount').html(dataobj.shippingrate);
						jQuery('.grand_total').html(dataobj.grandTotal);
						jQuery('.tax_amount').html(dataobj.taxAmount);					
						jQuery('#submit_btn').removeAttr('disabled');


					}
					else
					{
						
					}

				});	
				
								
			}else{

				jQuery('#billing_firstname').val('');
				jQuery('#billing_lastname').val('');
				
				jQuery('#billing_postcode').val('');				
				
				jQuery('#billing_city').val('');
				jQuery('#billing_telephone').val('');
				jQuery('#billing_mobile').val('');
				jQuery('#billing_street1').val('');
				
				jQuery('#billing_region_id').val('');
				jQuery('#billing_region').val('');
				jQuery('#billing_siab').show();

			}
		});
	}
	
	// function changeAddressSave(e)
	// {
	// 	if(e == true)
	// 	{
	
	// 		jQuery('#billing_save_in_address_book').val(1);
			
	// 	}
	// 	else{
	// 		jQuery('#billing_save_in_address_book').val(0);

	// 	}
	// }	
	
	function onchangeAddressSave()
	{
		
		jQuery("#billing_save_in_address_book").attr('checked', 'checked');
		jQuery("#billing_save_in_address_book").val(1);

	} 

	function changeAddressMode(e)
	{
		if(e == true)
		{
			jQuery('#billing_use_for_shipping_yes').val(1);

			jQuery('.shipping_address').hide();
		}
		else{
			jQuery('#billing_use_for_shipping_yes').val(0);
			jQuery('.shipping_address').show();

				jQuery('#shipping_address_form').change(function () {

					// var paymentdata = jQuery("#billing_address_form").serialize();
					var shippingdata = jQuery("#shipping_address_form").serialize();

						jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/savenewShipping/', 
							shippingdata,

						function (paymentdataretshippingaddress)
						{

						});
				});
		}
	}
	
	
</script>

 <script type="text/javascript">

 jQuery(".save_address_book").click(function (){
	var check = confirm("Do you want to save your new address?");
    if (check == true) {
    	jQuery('#billing_save_in_address_book').prop('checked', true);
    }
});

jQuery(".ship_address").click(function (){
	if(document.getElementById('billing_use_for_shipping_yes').checked) {
	    jQuery('#billing_use_for_shipping_yes').prop('checked', false);
	    jQuery('.shipping_address').show();
	    jQuery('.ship_address').html('Ship to this address');
	} else {
		jQuery('#billing_use_for_shipping_yes').prop('checked', true);
	    jQuery('.shipping_address').hide();
	    jQuery('.ship_address').html('Ship to different address');

	    var bill_fname = jQuery('#billing_firstname').val();
		jQuery('#shipping_firstname').val(bill_fname);

		var bill_lname = jQuery('#billing_lastname').val();
		jQuery('#shipping_lastname').val(bill_lname);

		var bill_country = jQuery('#billing_country_id').val();
		jQuery('#shipping_country_id').val(bill_country);

		var bill_postcode = jQuery('#billing_postcode').val();
		jQuery('#shipping_postcode').val(bill_postcode);

		var billing_region = jQuery('#billing_region_id').val();
		jQuery('#shipping_region_id').val(billing_region);

		var bill_city = jQuery('#billing_city').val();
		jQuery('#shipping_city').val(bill_city);

		jQuery.post('<?php echo Mage::getBaseurl(); ?>rracheckout/ajax/onepage', {region_id: billing_region, city_id: bill_city}, function(res){			
			jQuery("#shipping_city").html(res);
		});
		
		var bill_street = jQuery('#billing_street1').val();
		jQuery('#shipping_street1').val(bill_street);

		var bill_tel = jQuery('#billing_telephone').val();
		jQuery('#shipping_telephone').val(bill_tel);

		var bill_mobile = jQuery('#billing_mobile').val();
		jQuery('#shipping_mobile').val(bill_mobile);

		setTimeout(function(){
			jQuery('input[name=shippingmethod').prop('checked', true).trigger('click');
		
		}, 2000);

	
		check2(billing_region, bill_city);

	}
});

jQuery('#billing_save_in_address_book').change(function () {
	if(jQuery('#billing_save_in_address_book').is(':checked')){
    jQuery("#billing_save_in_address_book").val(1);

   		var shippingaddressdata = jQuery('#billing_address_form').serialize();
 		jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveanotherBilling/', 
			shippingaddressdata,

			function (shipdataretship)
			{
				var dataobj = jQuery.parseJSON(shipdataretship);

					if (dataobj.reload == true)
					{
									
							jQuery("#shippingmethod").click();
										
					}else{

						return;

					}
				

			}
		);


	}else{
    	jQuery("#billing_save_in_address_book").val(0);
	}

	jQuery("#billing_save_in_address_book").val(1);

 });


function onchangeBillingSave() //selecting city
{
	var paymentdata = jQuery('#billing_address_form').serialize();
	
	jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/savenewBilling/', 
	
	paymentdata,

	function (paymentdataretship)
	{

		var dataobj = jQuery.parseJSON(paymentdataretship);

		if (dataobj.reload == true)
		{
		
			jQuery("#shippingmethod").click();


		
		}else{

			return;
		
		}

	});	

}



jQuery('#billing_firstname').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_fname = jQuery('#billing_firstname').val();
		jQuery('#shipping_firstname').val(bill_fname);
	}
});

jQuery('#billing_lastname').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_lname = jQuery('#billing_lastname').val();
		jQuery('#shipping_lastname').val(bill_lname);
	}

});

jQuery('#billing_country_id').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_country = jQuery('#billing_country_id').val();
		jQuery('#shipping_country_id').val(bill_country);
	}

});

jQuery('#billing_postcode').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_postcode = jQuery('#billing_postcode').val();
		jQuery('#shipping_postcode').val(bill_postcode);
	}

});


jQuery('#billing_region_id').change(function() {
	var billing_region = jQuery('#billing_region_id').val();

	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		jQuery('#shipping_region_id').val(billing_region);

		setTimeout(function(){
			//jQuery('input[name=shippingmethod').prop('checked', true).trigger('click');
			
		}, 2000);
	}
});

jQuery('#billing_city').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_city = jQuery('#billing_city').val();
		jQuery('#shipping_city').val(bill_city);
		
		setTimeout(function(){
			jQuery('input[name=shippingmethod').prop('checked', true).trigger('click');
			
		}, 2000);
	}

});


jQuery('#billing_street1').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_street = jQuery('#billing_street1').val();
		jQuery('#shipping_street1').val(bill_street);
	}

});

jQuery('#billing_telephone').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_tel = jQuery('#billing_telephone').val();
		jQuery('#shipping_telephone').val(bill_tel);
	}

});

jQuery('#billing_mobile').change(function() {
	if(jQuery('#billing_use_for_shipping_yes').is(':checked')){
		var bill_mobile = jQuery('#billing_mobile').val();
		jQuery('#shipping_mobile').val(bill_mobile);
	}
});




//if customer has no address
jQuery(document).ready(function (){	

	var addressid = jQuery('#billing_address_id').val();
		if(addressid == 0){
			// alert(addressid);
				jQuery('#billing_address_form').change(function () {

					var newbillingdata = jQuery("#billing_address_form").serialize();
					 		jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveanotherBilling/', 
							newbillingdata,

							function (newbillingdata)
							{
								var dataobj = jQuery.parseJSON(newbillingdata);

									if (dataobj.reload == true)
									{
													
											//billing address is saved
											jQuery('#shipping_address_form').change(function () {
											var newshippingdata = jQuery("#shipping_address_form").serialize();
											 		jQuery.post( '<?php echo Mage::getBaseUrl();?>checkout/onepage/saveanotherShipping/', 
													newshippingdata,

													function (newshippingdata)
													{
														var dataobj = jQuery.parseJSON(newshippingdata);

															if (dataobj.reload == true)
															{
																			
																	// jQuery("#shippingmethod").click();
																	// alert(dataobj.reload);
																	// location.reload();
																	//billing address is saved
																				
															}else{

																return;

															}
														

													}
												);
											});
														
									}else{

										return;

									}
								

							}
						);
				});
			
		}

});


</script>



